import type { CurriculumArea } from "./types";

export const curriculumAreas: CurriculumArea[] = [
  {
    id: "foundations",
    title: "Foundations",
    slug: "foundations",
    level: "Foundation",
    order: 1,
    summary: "Build the sound vocabulary and articulation base before studying the rule families.",
    prerequisites: [],
    rules: [
      "what-is-tajweed",
      "why-tajweed-is-studied",
      "basic-arabic-pronunciation",
      "arabic-letters",
      "makharij-al-huruf",
      "sifaat-al-huruf",
      "heavy-and-light-letters",
      "intro-to-ghunnah",
    ],
  },
  {
    id: "noon-sakinah-tanween",
    title: "Noon Sakinah and Tanween",
    slug: "noon-sakinah-and-tanween",
    level: "Essential",
    order: 2,
    summary: "Study the core family of Noon Sakinah and Tanween rules through their conditions and sound distinctions.",
    prerequisites: ["makharij-al-huruf", "sifaat-al-huruf"],
    rules: [
      "noon-sakinah",
      "tanween",
      "izhar",
      "idgham",
      "idgham-with-ghunnah",
      "idgham-without-ghunnah",
      "iqlab",
      "ikhfa",
    ],
  },
  {
    id: "meem-sakinah",
    title: "Meem Sakinah",
    slug: "meem-sakinah",
    level: "Essential",
    order: 3,
    summary: "Study the three commonly taught Meem Sakinah cases in the standard teaching order.",
    prerequisites: ["makharij-al-huruf", "intro-to-ghunnah"],
    rules: [
      "meem-sakinah",
      "ikhfa-shafawi",
      "idgham-shafawi",
      "izhar-shafawi",
    ],
  },
  {
    id: "qalqalah",
    title: "Qalqalah",
    slug: "qalqalah",
    level: "Essential",
    order: 4,
    summary: "Recognize the letters and conditions for Qalqalah with attention to position and pronunciation.",
    prerequisites: ["makharij-al-huruf", "sifaat-al-huruf"],
    rules: [
      "qalqalah-letters",
      "qalqalah-when-sakin",
      "qalqalah-sughra",
      "qalqalah-kubra",
    ],
  },
  {
    id: "madd",
    title: "Madd",
    slug: "madd",
    level: "Intermediate",
    order: 5,
    summary: "Study the Madd family in a careful, stage-based sequence from natural elongation to advanced forms.",
    prerequisites: ["basic-arabic-pronunciation", "makharij-al-huruf"],
    rules: [
      "madd-tabii",
      "madd-badal",
      "madd-lin",
      "madd-arid-li-sukun",
      "madd-wajib-muttasil",
      "madd-jaiz-munfasil",
      "madd-lazim-kalimi",
      "madd-lazim-harfi",
    ],
  },
  {
    id: "lam-and-raa",
    title: "Lam and Raa Rules",
    slug: "lam-and-raa-rules",
    level: "Essential",
    order: 6,
    summary: "Understand the first Lam cases, then progress to the context-sensitive treatment of Raa.",
    prerequisites: ["makharij-al-huruf", "heavy-and-light-letters"],
    rules: [
      "lam-in-allah",
      "lam-shamsiyyah",
      "lam-qamariyyah",
      "raa-heavy-and-light",
    ],
  },
  {
    id: "waqf-ibtida",
    title: "Waqf and Ibtida",
    slug: "waqf-and-ibtida",
    level: "Essential",
    order: 7,
    summary: "Learn the foundations of stopping and restarting before studying detailed stop classifications.",
    prerequisites: ["basic-arabic-pronunciation", "madd-tabii"],
    rules: [
      "waqf",
      "ibtida",
      "major-stopping-concepts",
      "mushaf-stopping-symbols",
      "when-stopping-affects-pronunciation",
    ],
  },
  {
    id: "hamzah",
    title: "Hamzah",
    slug: "hamzah",
    level: "Intermediate",
    order: 8,
    summary: "Study the Hamzah cases relevant to beginning and linking recitation with qualified guidance.",
    prerequisites: ["basic-arabic-pronunciation", "ibtida"],
    rules: [
      "hamzat-al-wasl",
      "hamzat-al-qat",
      "beginning-with-hamzah",
    ],
  },
  {
    id: "advanced-recitation",
    title: "General Recitation Topics",
    slug: "general-recitation-topics",
    level: "Advanced",
    order: 9,
    summary: "Combine articulation, pronunciation precision, common confusions, and advanced recitation awareness.",
    prerequisites: ["makharij-al-huruf", "sifaat-al-huruf", "waqf"],
    rules: [
      "ghunnah",
      "tafkhim",
      "tarqiq",
      "articulation-and-clarity",
      "common-pronunciation-errors",
      "commonly-confused-letters",
    ],
  },
];
