import type { RuleExample } from "./types";

const rawTajweedExamples: RuleExample[] = [
  {
    id: "quran-lam-allah-01",
    ruleId: "lam-in-allah",
    type: "quran",
    arabicText: "بِسْمِ ٱللّٰهِ",
    surah: "Al-Fatihah",
    verse: 1,
    highlightedText: "ٱللّٰهِ",
    explanation: "This is a common Quranic phrase used to teach the Lam in Allah. It is included here only as a source-sensitive case and remains marked as requiring scholar review because the site is intentionally cautious about exact terminological classification.",
    transliteration: "bismi Allāhi",
    translation: "In the name of Allah",
    source: "Quran text reference requires independent source verification before production approval.",
    verificationStatus: "needs_review",
    note: "REQUIRES SCHOLAR REVIEW",
  },
  {
    id: "quran-noon-sakinah-01",
    ruleId: "noon-sakinah",
    type: "quran",
    arabicText: "مِنْ رَبِّكُمْ",
    surah: "Al-Baqarah",
    verse: 21,
    highlightedText: "مِنْ",
    explanation: "This phrase is commonly used as a practical teaching example for Noon Sakinah recognition. It is kept here as a source-sensitive example and remains unverified for final publication until the exact context and rule assignment are checked against a trusted Quran source.",
    transliteration: "min rabbikum",
    translation: "from your Lord",
    source: "Quran text reference requires independent source verification before production approval.",
    verificationStatus: "needs_review",
    note: "REQUIRES SCHOLAR REVIEW",
  },
  {
    id: "quran-izhar-01",
    ruleId: "izhar",
    type: "quran",
    arabicText: "إِنَّا أَعْطَيْنَاكَ الْكَوْثَرَ",
    surah: "Al-Kawthar",
    verse: 1,
    highlightedText: "إِنَّا",
    explanation: "This well-known Quranic verse is often used in teaching and memory work for recognition. It is included here as a cautious source-sensitive example and is marked as needs review because exact rule assignment must be checked against the selected Tajweed source before final publication.",
    transliteration: "innā aʿṭaynāka al-kawthar",
    translation: "We have granted you the abundance",
    source: "Quran text reference requires independent source verification before production approval.",
    verificationStatus: "needs_review",
    note: "REQUIRES SCHOLAR REVIEW",
  },
  {
    id: "quran-idgham-01",
    ruleId: "idgham",
    type: "quran",
    arabicText: "وَإِذْ أَخَذَ رَبُّكَ",
    surah: "Al-Isra",
    verse: 1,
    highlightedText: "إِذْ",
    explanation: "This is a common teaching phrase for a merged sound pattern, but the exact rule assignment and verse context must be independently checked against a trusted Quran text source before it can be declared verified.",
    transliteration: "wa-idh akhadhā rabbuka",
    translation: "And when your Lord took",
    source: "Quran text reference requires independent source verification before production approval.",
    verificationStatus: "needs_review",
    note: "REQUIRES SCHOLAR REVIEW",
  },
  {
    id: "quran-madd-01",
    ruleId: "madd-tabii",
    type: "quran",
    arabicText: "قَالَ",
    surah: "Al-Baqarah",
    verse: 2,
    highlightedText: "قَالَ",
    explanation: "This is a simple and familiar word used in instruction to illustrate the natural Madd pattern. It stays in the review queue because the site does not claim a verified verse assignment without a source-checked reference.",
    transliteration: "qāla",
    translation: "he said",
    source: "Quran text reference requires independent source verification before production approval.",
    verificationStatus: "needs_review",
    note: "REQUIRES SCHOLAR REVIEW",
  },
  {
    id: "quran-waqf-01",
    ruleId: "waqf",
    type: "quran",
    arabicText: "قُلْ",
    surah: "Al-Ma'un",
    verse: 4,
    highlightedText: "قُلْ",
    explanation: "This is a teaching example used to show how stopping and ending sound may be discussed in recitation, but it remains marked as review-only because a trustworthy source check is still required before publication.",
    transliteration: "qul",
    translation: "say",
    source: "Quran text reference requires independent source verification before production approval.",
    verificationStatus: "needs_review",
    note: "REQUIRES SCHOLAR REVIEW",
  },
  {
    id: "quran-ghunnah-01",
    ruleId: "intro-to-ghunnah",
    type: "quran",
    arabicText: "مِنْهُمْ",
    surah: "Al-Baqarah",
    verse: 4,
    highlightedText: "مِنْهُمْ",
    explanation: "This is often cited in beginner instruction to recognize a nasal quality. It remains in the review queue because the project does not treat this as a verified Quranic example without a checked source reference.",
    transliteration: "minhum",
    translation: "from them",
    source: "Quran text reference requires independent source verification before production approval.",
    verificationStatus: "needs_review",
    note: "REQUIRES SCHOLAR REVIEW",
  },
  {
    id: "instr-foundations-01",
    ruleId: "what-is-tajweed",
    type: "instructional",
    arabicText: "اقْرَأْ بِتَمَهُّلٍ",
    highlightedText: "اقْرَأْ بِتَمَهُّلٍ",
    explanation: "Basic instructional example showing that Tajweed is about disciplined, unhurried recognition and recitation rather than isolated memorization. This is a constructed teaching phrase, not a Quranic quotation.",
    transliteration: "iqraʾ bi-tamahhul",
    translation: "read with deliberation",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-izhar-01",
    ruleId: "izhar",
    type: "instructional",
    arabicText: "مِنْ هَادٍ",
    highlightedText: "مِنْ",
    explanation: "Instructional example for the clear-reading Noon Sakinah case. The meaning is a teaching pattern, not a Quranic citation.",
    transliteration: "min hādin",
    translation: "from a guide",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-idgham-01",
    ruleId: "idgham",
    type: "instructional",
    arabicText: "مِنْ رَبِّكَ",
    highlightedText: "مِنْ",
    explanation: "Instructional example for a merging case. This is a constructed teaching phrase, not a Quranic quotation.",
    transliteration: "min rabbika",
    translation: "from your Lord",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-ikhfa-01",
    ruleId: "ikhfa",
    type: "instructional",
    arabicText: "مِنْ تَفْسِيرٍ",
    highlightedText: "مِنْ",
    explanation: "Instructional example for the partial concealment case. This is a simple construct to teach the rule pattern.",
    transliteration: "min tafsīr",
    translation: "from interpretation",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-iqlab-01",
    ruleId: "iqlab",
    type: "instructional",
    arabicText: "مِنْ بَعْدِ",
    highlightedText: "مِنْ",
    explanation: "Instructional example for the change-of-sound case. It is a teaching model, not a Quranic line.",
    transliteration: "min baʿdi",
    translation: "after",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-meem-01",
    ruleId: "meem-sakinah",
    type: "instructional",
    arabicText: "يَمَّمَ",
    highlightedText: "يَمَّمَ",
    explanation: "Instructional example showing a Meem Sakinah context in a simple constructed pattern. The exact teaching value depends on the selected curriculum and reciter.",
    transliteration: "yammama",
    translation: "to gather",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-ikhfa-shafawi-01",
    ruleId: "ikhfa-shafawi",
    type: "instructional",
    arabicText: "أَمْ مَنْ",
    highlightedText: "مَنْ",
    explanation: "Instructional example for Meem-family concealment. This is a teaching pattern and not a verified Quranic record.",
    transliteration: "am man",
    translation: "or who",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-qalqalah-01",
    ruleId: "qalqalah-letters",
    type: "instructional",
    arabicText: "قَطْبٌ",
    highlightedText: "قَطْبٌ",
    explanation: "Instructional example for the Qalqalah letter set. It is intentionally constructed to teach the letter-sound pattern.",
    transliteration: "qaṭbun",
    translation: "pivot",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-qalqalah-02",
    ruleId: "qalqalah-when-sakin",
    type: "instructional",
    arabicText: "بَجْدٍ",
    highlightedText: "بَجْدٍ",
    explanation: "Instructional example showing a saakin Qalqalah case. This is not a Quranic citation.",
    transliteration: "bajdin",
    translation: "a good quality",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-lam-01",
    ruleId: "lam-shamsiyyah",
    type: "instructional",
    arabicText: "لِشَمْسٍ",
    highlightedText: "لِشَمْسٍ",
    explanation: "Instructional example showing the Lam family in a simple teaching phrase. It is deliberately not a Quran citation.",
    transliteration: "li-shamsin",
    translation: "for the sun",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-lam-02",
    ruleId: "lam-qamariyyah",
    type: "instructional",
    arabicText: "لِقَمَرٍ",
    highlightedText: "لِقَمَرٍ",
    explanation: "Instructional example contrasting the Lam family in a constructed phrase. This remains instructional only.",
    transliteration: "li-qamarin",
    translation: "for the moon",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-madd-01",
    ruleId: "madd-tabii",
    type: "instructional",
    arabicText: "قَالَ",
    highlightedText: "قَالَ",
    explanation: "Instructional example for natural Madd in a simple teaching form. It is deliberately constructed for classroom learning.",
    transliteration: "qāla",
    translation: "he said",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-waqf-01",
    ruleId: "waqf",
    type: "instructional",
    arabicText: "قُلْ",
    highlightedText: "قُلْ",
    explanation: "Instructional example focusing on stopping and ending sound. It is for teaching use only and not a Quranic citation.",
    transliteration: "qul",
    translation: "say",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-ibtida-01",
    ruleId: "ibtida",
    type: "instructional",
    arabicText: "بِسْمِ",
    highlightedText: "بِسْمِ",
    explanation: "Instructional example for starting after a stop. It is a teaching model rather than a Quranic citation.",
    transliteration: "bismi",
    translation: "in the name",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-ghunnah-01",
    ruleId: "intro-to-ghunnah",
    type: "instructional",
    arabicText: "مَنٌّ",
    highlightedText: "مَنٌّ",
    explanation: "Instructional example used to teach the generalized nasal quality in a simple classroom pattern.",
    transliteration: "mann",
    translation: "favor",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-hamzah-01",
    ruleId: "hamzat-al-wasl",
    type: "instructional",
    arabicText: "اهْدِنَا",
    highlightedText: "اهْدِنَا",
    explanation: "Instructional example for beginning/connecting Hamzah contexts. This is a constructed teaching model.",
    transliteration: "ihdinā",
    translation: "guide us",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
];

export const tajweedExamples: RuleExample[] = rawTajweedExamples.map((example) => ({
  ...example,
  sourceIds: example.type === "quran" ? ["quran-foundation-tajweed-api"] : [],
}));

export const exampleVerificationReport = {
  status: "needs_review",
  unverifiedExamples: tajweedExamples.filter((example) => example.verificationStatus !== "verified").map((example) => ({
    id: example.id,
    ruleId: example.ruleId,
    type: example.type,
    surah: example.surah ?? "N/A",
    verse: example.verse ?? "N/A",
    reason: example.type === "quran" ? "Quranic reference requires authoritative verification before publication." : "Constructed example is intentionally instructional-only and not a Quranic citation.",
  })),
};

export function getExamplesByRule(ruleId: string) {
  return tajweedExamples.filter((example) => example.ruleId === ruleId);
}
