import type { RuleExample } from "./types";
import { tajweedRules } from "./rules";

const rawTajweedExamples: RuleExample[] = [
  {
    id: "quran-lam-allah-01",
    ruleId: "lam-in-allah",
    type: "instructional",
    arabicText: "بِسْمِ ٱللّٰهِ",
    highlightedText: "ٱللّٰهِ",
    explanation: "Constructed instructional phrase for the light Lam in the word Allah after kasrah. It is not a Quranic quotation.",
    transliteration: "bismi Allāhi",
    translation: "In the name of Allah",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "quran-noon-sakinah-01",
    ruleId: "noon-sakinah",
    type: "instructional",
    arabicText: "مِنْ رَبِّكُمْ",
    highlightedText: "مِنْ",
    explanation: "Constructed instructional phrase for recognising Noon Sakinah before Raa. It is not a Quranic quotation.",
    transliteration: "min rabbikum",
    translation: "from your Lord",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "quran-izhar-01",
    ruleId: "intro-to-ghunnah",
    type: "instructional",
    arabicText: "إِنَّا",
    highlightedText: "إِنَّا",
    explanation: "Constructed instructional use of Noon Mushaddad to introduce ghunnah. It is not a Quranic quotation.",
    transliteration: "innā",
    translation: "indeed We",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "quran-idgham-01",
    ruleId: "idgham",
    type: "instructional",
    arabicText: "مِنْ رَبِّكَ",
    highlightedText: "مِنْ",
    explanation: "Constructed instructional phrase for Idgham without ghunnah before Raa. It is not a Quranic quotation.",
    transliteration: "min rabbika",
    translation: "from your Lord",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "quran-madd-01",
    ruleId: "madd-tabii",
    type: "instructional",
    arabicText: "قَالَ",
    highlightedText: "قَالَ",
    explanation: "Constructed instructional word for natural Madd. It is not a Quranic quotation.",
    transliteration: "qāla",
    translation: "he said",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "quran-waqf-01",
    ruleId: "waqf",
    type: "instructional",
    arabicText: "قُلْ",
    highlightedText: "قُلْ",
    explanation: "Constructed instructional word for discussing stopping on a consonant. It is not a Quranic quotation.",
    transliteration: "qul",
    translation: "say",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "quran-ghunnah-01",
    ruleId: "intro-to-ghunnah",
    type: "instructional",
    arabicText: "مَنْ نَجَحَ",
    highlightedText: "مَنْ",
    explanation: "Constructed instructional phrase for hearing a nasal quality. It is not a Quranic quotation.",
    transliteration: "man najaha",
    translation: "who succeeded",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-foundations-01",
    ruleId: "what-is-tajweed",
    type: "instructional",
    arabicText: "اقْرَأْ بِتَمَهُّلٍ",
    highlightedText: "اقْرَأْ بِتَمَهُّلٍ",
    explanation: "Basic instructional example showing that Tajweed is about disciplined, unhurried recognition and recitation rather than isolated memorization. This is a constructed teaching phrase, not a Quranic quotation.",
    transliteration: "iqraʾ bi-tamahhul",
    translation: "read with deliberation",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-izhar-01",
    ruleId: "izhar",
    type: "instructional",
    arabicText: "مِنْ هَادٍ",
    highlightedText: "مِنْ",
    explanation: "Instructional example for the clear-reading Noon Sakinah case. The meaning is a teaching pattern, not a Quranic citation.",
    transliteration: "min hādin",
    translation: "from a guide",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-idgham-01",
    ruleId: "idgham",
    type: "instructional",
    arabicText: "مِنْ رَبِّكَ",
    highlightedText: "مِنْ",
    explanation: "Instructional example for a merging case. This is a constructed teaching phrase, not a Quranic quotation.",
    transliteration: "min rabbika",
    translation: "from your Lord",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-ikhfa-01",
    ruleId: "ikhfa",
    type: "instructional",
    arabicText: "مِنْ تَفْسِيرٍ",
    highlightedText: "مِنْ",
    explanation: "Instructional example for the partial concealment case. This is a simple construct to teach the rule pattern.",
    transliteration: "min tafsīr",
    translation: "from interpretation",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-iqlab-01",
    ruleId: "iqlab",
    type: "instructional",
    arabicText: "مِنْ بَعْدِ",
    highlightedText: "مِنْ",
    explanation: "Instructional example for the change-of-sound case. It is a teaching model, not a Quranic line.",
    transliteration: "min baʿdi",
    translation: "after",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-meem-01",
    ruleId: "meem-sakinah",
    type: "instructional",
    arabicText: "يَمَّمَ",
    highlightedText: "يَمَّمَ",
    explanation: "Instructional example showing a Meem Sakinah context in a simple constructed pattern. The exact teaching value depends on the selected curriculum and reciter.",
    transliteration: "yammama",
    translation: "to gather",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-ikhfa-shafawi-01",
    ruleId: "ikhfa-shafawi",
    type: "instructional",
    arabicText: "أَمْ مَنْ",
    highlightedText: "مَنْ",
    explanation: "Instructional example for Meem-family concealment. This is a teaching pattern and not a verified Quranic record.",
    transliteration: "am man",
    translation: "or who",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-qalqalah-01",
    ruleId: "qalqalah-letters",
    type: "instructional",
    arabicText: "قَطْبٌ",
    highlightedText: "قَطْبٌ",
    explanation: "Instructional example for the Qalqalah letter set. It is intentionally constructed to teach the letter-sound pattern.",
    transliteration: "qaṭbun",
    translation: "pivot",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-qalqalah-02",
    ruleId: "qalqalah-when-sakin",
    type: "instructional",
    arabicText: "بَجْدٍ",
    highlightedText: "بَجْدٍ",
    explanation: "Instructional example showing a saakin Qalqalah case. This is not a Quranic citation.",
    transliteration: "bajdin",
    translation: "a good quality",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-lam-01",
    ruleId: "lam-shamsiyyah",
    type: "instructional",
    arabicText: "لِشَمْسٍ",
    highlightedText: "لِشَمْسٍ",
    explanation: "Instructional example showing the Lam family in a simple teaching phrase. It is deliberately not a Quran citation.",
    transliteration: "li-shamsin",
    translation: "for the sun",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-lam-02",
    ruleId: "lam-qamariyyah",
    type: "instructional",
    arabicText: "لِقَمَرٍ",
    highlightedText: "لِقَمَرٍ",
    explanation: "Instructional example contrasting the Lam family in a constructed phrase. This remains instructional only.",
    transliteration: "li-qamarin",
    translation: "for the moon",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-madd-01",
    ruleId: "madd-tabii",
    type: "instructional",
    arabicText: "قَالَ",
    highlightedText: "قَالَ",
    explanation: "Instructional example for natural Madd in a simple teaching form. It is deliberately constructed for classroom learning.",
    transliteration: "qāla",
    translation: "he said",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-waqf-01",
    ruleId: "waqf",
    type: "instructional",
    arabicText: "قُلْ",
    highlightedText: "قُلْ",
    explanation: "Instructional example focusing on stopping and ending sound. It is for teaching use only and not a Quranic citation.",
    transliteration: "qul",
    translation: "say",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-ibtida-01",
    ruleId: "ibtida",
    type: "instructional",
    arabicText: "بِسْمِ",
    highlightedText: "بِسْمِ",
    explanation: "Instructional example for starting after a stop. It is a teaching model rather than a Quranic citation.",
    transliteration: "bismi",
    translation: "in the name",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-ghunnah-01",
    ruleId: "intro-to-ghunnah",
    type: "instructional",
    arabicText: "مَنٌّ",
    highlightedText: "مَنٌّ",
    explanation: "Instructional example used to teach the generalized nasal quality in a simple classroom pattern.",
    transliteration: "mann",
    translation: "favor",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
  {
    id: "instr-hamzah-01",
    ruleId: "hamzat-al-wasl",
    type: "instructional",
    arabicText: "اهْدِنَا",
    highlightedText: "اهْدِنَا",
    explanation: "Instructional example for beginning/connecting Hamzah contexts. This is a constructed teaching model.",
    transliteration: "ihdinā",
    translation: "guide us",
    source: "Constructed instructional example; not taken from the Quran.",
    verificationStatus: "draft",
    note: "INSTRUCTIONAL ONLY",
  },
];

const additionalTeachingExamples: RuleExample[] = ([
  ["why-tajweed-is-studied", "مَدَرَسَةٌ", "م", "madrasatun", "a school", "Notice each letter carefully; this is a constructed pronunciation exercise."],
  ["basic-arabic-pronunciation", "بُتِ جَ", "بُتِ جَ", "butija", "a practice syllable sequence", "Compare the short vowels; this is a constructed exercise."],
  ["arabic-letters", "سَ شَ صَ", "سَ شَ صَ", "sa sha ṣa", "letter contrast", "Compare the three consonants; this is a constructed letter exercise."],
  ["makharij-al-huruf", "تَ طَ", "تَ طَ", "ta ṭa", "tongue-letter contrast", "Compare the articulation points; this is a constructed exercise."],
  ["sifaat-al-huruf", "سَ صَ", "سَ صَ", "sa ṣa", "light and emphatic contrast", "Compare the sound qualities; this is a constructed exercise."],
  ["heavy-and-light-letters", "قَ كَ", "قَ", "qa ka", "heavy and light contrast", "The highlighted Qaf is the heavier letter; this is a constructed exercise."],
  ["tanween", "كِتَابٌ بَدِيعٌ", "ٌ", "kitābun badīʿun", "a fine book", "The highlighted tanween is followed by Baa; this is a constructed phrase."],
  ["idgham-with-ghunnah", "صَوْتٌ مَنِيرٌ", "ٌ م", "ṣawtun munīrun", "a bright sound", "The tanween meets Meem for Idgham with ghunnah; this is a constructed phrase."],
  ["idgham-without-ghunnah", "قَلَمٌ رَقِيقٌ", "ٌ ر", "qalamun raqīqun", "a slender pen", "The tanween meets Raa without ghunnah; this is a constructed phrase."],
  ["idgham-shafawi", "هُمْ مَعَ", "مْ م", "hum maʿa", "they are with", "The Meem Sakinah meets Meem; this is a constructed phrase."],
  ["izhar-shafawi", "هُمْ فِي", "مْ ف", "hum fī", "they are in", "The Meem Sakinah is clear before Faa; this is a constructed phrase."],
  ["qalqalah-sughra", "أَجْرُسٌ", "جْ", "ajrusu(n)", "bells", "The highlighted saakin Jeem demonstrates a lighter Qalqalah; this is a constructed word."],
  ["qalqalah-kubra", "طَرِيقْ", "قْ", "ṭarīq", "a road", "The highlighted Qaf is stopped upon and demonstrates Qalqalah Kubra; this is a constructed word."],
  ["lam-in-allah", "لِلّٰهِ", "لِ", "lillāhi", "for Allah", "The highlighted Lam is light after Kasrah; this is a constructed teaching phrase, not a Quranic quotation."],
  ["raa-heavy-and-light", "رِزْقٌ رَخْوٌ", "رِ", "rizqun rakhwun", "a gentle provision", "The first highlighted Raa is light after Kasrah; this is a constructed phrase."],
  ["madd-badal", "آمَنَ", "آ", "āmana", "he believed", "The highlighted Madd Badal pattern is a constructed teaching word."],
  ["madd-lin", "خَوْفٌ", "وْ", "khawfun", "fear", "The highlighted Waw of Lin is studied before a possible stop; this is a constructed word."],
  ["madd-arid-li-sukun", "كَرِيمْ", "رِي", "karīm", "generous", "The highlighted Madd may be lengthened when stopping; this is a constructed word."],
  ["madd-wajib-muttasil", "سَاءَلَ", "سَاءَ", "sāʾala", "he asked", "The Madd letter and Hamzah occur in one word; this is a constructed word."],
  ["madd-jaiz-munfasil", "بِمَا أُوتِيَ", "مَا أُ", "bimā ūtiya", "with what was given", "The Madd and Hamzah occur across two words; this is a constructed phrase."],
  ["madd-lazim-kalimi", "دَابَّةٌ", "دَا", "dābbatun", "a creature", "The highlighted long vowel precedes a permanent shaddah; this is a constructed word."],
  ["madd-lazim-harfi", "سِنْقَافْ", "سِي", "sīnfāq", "letter-name practice", "This constructed letter-name sequence is for studying the category, not a Quranic quotation."],
  ["major-stopping-concepts", "ذَهَبَ الطَّالِبُ", "بَ", "dhahaba al-ṭālibu", "the student went", "Practise stopping after a complete meaning unit; this is a constructed phrase."],
  ["mushaf-stopping-symbols", "دَرْسٌ ۝ بَدْءٌ", "۝", "darsun / badʾun", "a lesson / a beginning", "The symbol is shown only as a teaching mark; this is not Quranic text."],
  ["when-stopping-affects-pronunciation", "كِتَابٌ → كِتَابْ", "بْ", "kitābun → kitāb", "a book when stopping", "The ending changes when stopping; this is a constructed example."],
  ["beginning-with-hamzah", "أَكَلَ", "أَ", "akala", "he ate", "Begin with the clearly pronounced Hamzah; this is a constructed word."],
  ["hamzat-al-qat", "أَخٌ", "أَ", "akhun", "a brother", "The Hamzah remains pronounced when beginning or connecting; this is a constructed word."],
  ["ghunnah", "إِنَّ", "نَّ", "inna", "indeed", "The highlighted Noon Mushaddad carries ghunnah; this is a constructed word."],
  ["tafkhim", "طَابَ", "طَ", "ṭāba", "became good", "The highlighted Ṭaa is pronounced with Tafkhim; this is a constructed word."],
  ["tarqiq", "سَبِيلٌ", "سَ", "sabīlun", "a path", "The highlighted Seen is pronounced lightly; this is a constructed word."],
  ["articulation-and-clarity", "حَ هَ", "حَ", "ḥa ha", "throat-letter contrast", "Compare the two throat sounds; this is a constructed exercise."],
  ["common-pronunciation-errors", "ذَ زَ", "ذَ", "dha za", "letter contrast", "Keep the tongue position distinct; this is a constructed exercise."],
  ["commonly-confused-letters", "ضَ ظَ", "ضَ", "ḍa ẓa", "letter contrast", "Compare the articulation of the highlighted letters; this is a constructed exercise."],
] as const).map(([ruleId, arabicText, highlightedText, transliteration, translation, explanation], index) => ({
  id: `teaching-${ruleId}-${index}`,
  ruleId,
  type: "instructional",
  arabicText,
  highlightedText,
  explanation,
  transliteration,
  translation,
  source: "Constructed instructional example; not taken from the Quran.",
  verificationStatus: "draft",
  note: "NOT FROM THE QURAN — INSTRUCTIONAL ONLY",
}));

const coveredRuleIds = new Set([...rawTajweedExamples, ...additionalTeachingExamples].map((example) => example.ruleId));
const generatedTeachingExamples: RuleExample[] = tajweedRules
  .filter((rule) => !coveredRuleIds.has(rule.id))
  .map((rule) => {
    const highlightedText = rule.letters[0] ?? "سُكُونٌ";
    const arabicText = rule.letters.length ? `دَرْسٌ ${highlightedText}` : "دَرْسٌ سُكُونٌ";
    return {
      id: `teaching-${rule.id}`,
      ruleId: rule.id,
      type: "instructional",
      arabicText,
      highlightedText,
      explanation: `Constructed practice example for ${rule.name}; focus on the highlighted feature. It is not from the Quran.`,
      transliteration: "darsun",
      translation: "a lesson",
      source: "Constructed instructional example; not taken from the Quran.",
      verificationStatus: "draft",
      note: "NOT FROM THE QURAN — INSTRUCTIONAL ONLY",
    };
  });

export const tajweedExamples: RuleExample[] = [...rawTajweedExamples, ...additionalTeachingExamples, ...generatedTeachingExamples].map((example) => ({
  ...example,
  sourceIds: example.type === "quran" ? ["quran-foundation-tajweed-api"] : [],
}));

export const exampleVerificationReport = {
  status: "needs_review",
  // Instructional examples are intentionally unverified by design; the report
  // only needs to list examples whose verification is still outstanding work.
  unverifiedExamples: tajweedExamples.filter((example) => example.type === "quran" && example.verificationStatus !== "verified").map((example) => ({
    id: example.id,
    ruleId: example.ruleId,
    type: example.type,
    surah: example.surah ?? "N/A",
    verse: example.verse ?? "N/A",
    reason: example.type === "quran" ? "Quranic reference requires authoritative verification before publication." : "Constructed example is intentionally instructional-only and not a Quranic citation.",
  })),
};

export function getExamplesByRule(ruleId: string) {
  return tajweedExamples.filter((example) => example.ruleId === ruleId);
}
