import type { TajweedRuleRecord } from "./types";

export const tajweedRules: TajweedRuleRecord[] = [
  {
    id: "what-is-tajweed",
    slug: "what-is-tajweed",
    name: "What is Tajweed?",
    arabicName: "التجويد",
    category: "Foundations",
    level: "Foundation",
    difficultyScore: 1,
    shortDefinition: "Tajweed is the disciplined way of reciting the Quran with correct pronunciation, articulation, and rhythm.",
    detailedExplanation: "Tajweed is the science of preserving the correct delivery of the Quranic text by paying attention to articulation points, letter qualities, length, pause, and the sound of each letter. It is not a separate text to be added to the Quran; it is a way of reciting the revealed words in a precise and respectful manner. A serious learner starts by understanding the Arabic sound system, then applies the rules gradually under qualified guidance.",
    whenItOccurs: "This foundational concept is relevant throughout recitation and is not limited to a single passage or verse.",
    letters: [],
    pronunciation: "The goal is not to imitate an English sound but to read with accurate Arabic articulation and appropriate timing.",
    commonMistakes: [
      "Treating Tajweed as a list of isolated labels without listening practice.",
      "Ignoring articulation and focusing only on memorization.",
      "Assuming the writing of a rule is enough to master the pronunciation.",
    ],
    memoryTip: "Think of Tajweed as the practical discipline that protects the Quranic sound from distortion.",
    prerequisites: [],
    relatedRules: ["basic-arabic-pronunciation", "makharij-al-huruf", "why-tajweed-is-studied"],
    quranExamples: [],
    practiceQuestions: [
      "Why is Tajweed studied alongside Quran recitation?",
      "What is the difference between reading Quran and reciting it with Tajweed?",
    ],
    faq: [
      { question: "Is Tajweed only for advanced readers?", answer: "No. It begins with the foundations and is studied progressively from the earliest stage of learning recitation." },
      { question: "Do I need to memorize every rule before reciting?", answer: "No. Learners gradually build recognition and application, usually with hearing, repetition, and teacher guidance." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This is a general conceptual statement. It should be reviewed against a standard curriculum definition and used consistently across the site."],
  },
  {
    id: "why-tajweed-is-studied",
    slug: "why-tajweed-is-studied",
    name: "Why Tajweed is Studied",
    arabicName: "أهمية التجويد",
    category: "Foundations",
    level: "Foundation",
    difficultyScore: 1,
    shortDefinition: "Tajweed is studied to protect the Quranic sound, improve accuracy, and support respectful recitation.",
    detailedExplanation: "The Quran was revealed in Arabic, and the letters carry precise articulation and sound qualities. Tajweed helps a learner preserve the meanings and pronunciation that the Quranic wording requires. It also supports consistency in reading and helps the learner listen more carefully to the sound of the letters, vowels, and pauses. It is not a theoretical subject only; it is tied directly to recitation practice and sound discipline.",
    whenItOccurs: "This principle applies all the time, from first introduction to advanced recitation.",
    letters: [],
    pronunciation: "A learner should move from correct recognition to correct sound production with repeated listening and recitation.",
    commonMistakes: [
      "Studying rules without connecting them to sound.",
      "Treating Tajweed as optional decoration instead of a disciplined reading practice.",
    ],
    memoryTip: "Tajweed protects the recitation from distortion and keeps the reading aligned with the revealed text.",
    prerequisites: [],
    relatedRules: ["what-is-tajweed", "makharij-al-huruf", "waqf"],
    quranExamples: [],
    practiceQuestions: [
      "Why is articulation important in Quran recitation?",
      "Why should a learner listen to a qualified reciter?",
    ],
    faq: [
      { question: "Is Tajweed only about correctness?", answer: "It is also about care, reverence, and sound discipline in reading the Quran." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This content is a general educational framing. It should be reviewed for tone and doctrinal framing before publication."],
  },
  {
    id: "basic-arabic-pronunciation",
    slug: "basic-arabic-pronunciation",
    name: "Basic Arabic Pronunciation",
    arabicName: "الحركات والسكون",
    category: "Foundations",
    level: "Foundation",
    difficultyScore: 1,
    shortDefinition: "This area covers the basic sounds, vowels, and emphasis patterns that make up Arabic reading before later Tajweed rules are applied.",
    detailedExplanation: "A learner cannot correctly apply later rules without understanding the basic building blocks: the Arabic letters, vowel signs, and the idea of a letter being saakin (without a vowel) or mutaharrik (with a vowel). These basics support recognition of Noon Sakinah, Tanween, Madd, and more advanced forms. The learner should become comfortable with the sounds represented by fatha, damma, kasra, and the concept of movement and rest.",
    whenItOccurs: "This is the foundational layer for all Tajweed practice and is used in every later rule.",
    letters: ["أ", "ا", "ب", "ت", "ي"],
    pronunciation: "The learner should focus on clear vowel articulation and on hearing the difference between a vowel and a letter that is at rest.",
    commonMistakes: [
      "Ignoring vowel signs and reading by memory instead of sound.",
      "Assuming that all letters are equally affected by the same vowel use.",
    ],
    memoryTip: "Every Tajweed rule begins with a sound building block: a letter, a vowel, or a pause.",
    prerequisites: ["arabic-letters"],
    relatedRules: ["noon-sakinah", "madd-tabii", "waqf"],
    quranExamples: [],
    practiceQuestions: [
      "What is the difference between a mutaharrik and a saakin letter?",
      "Why do learners need to study vowels before the rule families?",
    ],
    faq: [
      { question: "Do I need to know advanced Arabic to start?", answer: "No. A basic understanding of Arabic script and pronunciation is enough to begin with structured practice." },
    ],
    sources: ["mcec-quran-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Saturday School Quran Curriculum"],
    reviewNotes: ["This is an intentionally broad foundational statement and should be checked against the selected teaching sequence before publication."],
  },
  {
    id: "arabic-letters",
    slug: "arabic-letters",
    name: "Arabic Letters",
    arabicName: "حروف الهجاء",
    category: "Foundations",
    level: "Foundation",
    difficultyScore: 1,
    shortDefinition: "Arabic letters are the basic unit of reading. Learners must know their shapes, order, and basic phonetic distinctions before studying rule families.",
    detailedExplanation: "The Arabic alphabet is the foundation of reading the Quran. Each letter has an articulation point, sound, and set of qualities. Without this foundation, Tajweed becomes a memorized label rather than a sound discipline. The learner begins by recognizing the letters, their shapes, and their basic place of production.",
    whenItOccurs: "This applies at the start of learning and remains essential while reading with Tajweed.",
    letters: ["ا", "ب", "ت", "ث", "ج", "ح", "خ", "د", "ذ", "ر", "ز", "س", "ش", "ص", "ض", "ط", "ظ", "ع", "غ", "ف", "ق", "ك", "ل", "م", "ن", "ه", "و", "ي"],
    pronunciation: "Pronunciation begins with correct letter recognition and careful listening to the articulation point.",
    commonMistakes: [
      "Memorizing letters without listening to their sound.",
      "Confusing letters that share similar shapes or sounds.",
    ],
    memoryTip: "Know the letters before studying the rules. A rule cannot be applied correctly if the basic letters are not recognized.",
    prerequisites: [],
    relatedRules: ["makharij-al-huruf", "sifaat-al-huruf", "basic-arabic-pronunciation"],
    quranExamples: [],
    practiceQuestions: [
      "Why is the Arabic alphabet important before Tajweed rules?",
      "How does letter recognition support Makharij and Sifaat?",
    ],
    faq: [
      { question: "Do I need full Arabic fluency before Tajweed?", answer: "No, but you do need a working knowledge of the Arabic letters and basic reading signs." },
    ],
    sources: ["mcec-quran-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Saturday School Quran Curriculum"],
    reviewNotes: ["A broad foundational explanation is acceptable here, but it should be cross-checked for its exact educational framing and wording."],
  },
  {
    id: "makharij-al-huruf",
    slug: "makharij-al-huruf",
    name: "Makharij al-Huruf",
    arabicName: "مخارج الحروف",
    category: "Foundations",
    level: "Foundation",
    difficultyScore: 2,
    shortDefinition: "Makharij refers to the articulation points of the letters, where the sound is produced in the mouth or throat.",
    detailedExplanation: "This is one of the most important foundations in Tajweed. Each Arabic letter is produced from a particular place of articulation, and recognizing those points helps a learner form the correct sound. The science of Makharij is the basis for many later rules because a letter can be confused with another when the articulation point is not properly understood. The articulation points are taught progressively, often beginning with the throat, lips, tongue, and nasal area.",
    whenItOccurs: "Makharij is used in every letter sound, making it a foundation for all later Tajweed rules.",
    letters: ["أ", "ح", "خ", "ع", "غ", "ق", "ك", "ت", "د", "ط", "ب", "م", "ف", "ل", "ر", "ن", "ي", "س", "ص", "ش"],
    pronunciation: "A learner should focus on the correct place of sound production and not on guesswork or transliteration alone.",
    commonMistakes: [
      "Pronouncing a letter based only on the letter name or an English approximation.",
      "Ignoring the place of articulation when comparing similar sounds.",
    ],
    memoryTip: "When a rule feels difficult, identify the letter first, then ask where the sound is produced.",
    prerequisites: ["arabic-letters"],
    relatedRules: ["sifaat-al-huruf", "strong-letter-qualities", "qalqalah-letters"],
    quranExamples: [],
    practiceQuestions: [
      "Why are Makharij considered essential before advanced rules?",
      "How do articulation points help distinguish similar letters?",
    ],
    faq: [
      { question: "Can I learn Makharij from a book alone?", answer: "You can study the concept in writing, but correct production is best learned with a teacher or a verified audio demonstration." },
    ],
    sources: ["recite-with-love-curriculum", "mcec-quran-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum", "Saturday School Quran Curriculum"],
    reviewNotes: ["This is an accepted foundational concept, but the precise classification of articulation points should be reviewed before being used as a final educational claim."],
  },
  {
    id: "sifaat-al-huruf",
    slug: "sifaat-al-huruf",
    name: "Sifaat al-Huruf",
    arabicName: "صفات الحروف",
    category: "Foundations",
    level: "Foundation",
    difficultyScore: 2,
    shortDefinition: "Sifaat are the qualities of letters: the sound characteristics that help distinguish one letter from another and explain how letter sounds behave in context.",
    detailedExplanation: "Once a learner knows where a letter is produced, the next step is understanding its qualities. This includes lightness, heaviness, softness, roughness, and other characteristics that affect how the sound is heard and produced. These qualities are essential for rules such as Tafkhim, Tarqiq, and Qalqalah, and they also support recognition in Noon, Meem, Lam, and Raa cases.",
    whenItOccurs: "This concept is used throughout recitation whenever the learner compares the sound of two letters or studies a rule that depends on quality.",
    letters: ["ق", "ك", "ج", "ش", "ر", "ل", "ص", "ض", "ط", "ظ"],
    pronunciation: "The learner listens for qualities such as heaviness and lightness rather than guessing from a written label alone.",
    commonMistakes: [
      "Reducing Sifaat to a simplistic list without hearing the actual contrast.",
      "Using word meaning as a substitute for correct sound quality.",
    ],
    memoryTip: "Makharij tells you where a sound is produced; Sifaat tells you what the sound feels like.",
    prerequisites: ["makharij-al-huruf"],
    relatedRules: ["heavy-and-light-letters", "qalqalah-letters", "lam-shamsiyyah"],
    quranExamples: [],
    practiceQuestions: [
      "What is the relationship between Makharij and Sifaat?",
      "How do Sifaat support recognition of heavy and light letters?",
    ],
    faq: [
      { question: "Are Sifaat the same as letter names?", answer: "No. They are qualities or characteristics of the sound, not just the names of letters." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This is a standard foundational explanation but should be reviewed for terminology and specific classification details before publication."],
  },
  {
    id: "heavy-and-light-letters",
    slug: "heavy-and-light-letters",
    name: "Heavy and Light Letters",
    arabicName: "التفخيم والترقيق",
    category: "Foundations",
    level: "Foundation",
    difficultyScore: 2,
    shortDefinition: "Heavy and light letters are a basic distinction in Arabic pronunciation: some letters are heard with a fuller, heavier sound, while others are lighter and more open.",
    detailedExplanation: "The terms Tafkhim and Tarqiq describe the heavier and lighter sounding qualities of letters. These qualities are shaped by articulation and voice resonance, and they are important for later rules such as Lam and Raa. A learner should not reduce the whole issue to a simple formula. Heavy and light qualities are learned by listening carefully and by comparing sound patterns under qualified guidance.",
    whenItOccurs: "This concept applies throughout recitation and is especially important in Lam, Raa, and the general understanding of letter quality.",
    letters: ["ق", "ط", "ص", "ض", "ظ", "ع", "غ", "خ", "ر", "ل"],
    pronunciation: "A serious learner listens for the difference between a fuller, denser sound and a lighter, more open sound; this is not a matter of guesswork or English word meaning.",
    commonMistakes: [
      "Reducing Tafkhim and Tarqiq to a single rule without context.",
      "Treating every letter with a fatha as automatically heavy or light.",
    ],
    memoryTip: "Heavy and light is a sound quality, not simply a letter list to memorize without hearing.",
    prerequisites: ["makharij-al-huruf", "sifaat-al-huruf"],
    relatedRules: ["lam-shamsiyyah", "raa-heavy-and-light", "tafkhim"],
    quranExamples: [],
    practiceQuestions: [
      "Why is heaviness and lightness a sound issue rather than a text-only issue?",
      "How are Lam and Raa related to this foundation?",
    ],
    faq: [
      { question: "Is heavy and light always determined by the vowel sign?", answer: "No. It is not reduced to a single simplistic formula and must be studied with the full context and learned guidance." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This entry is intentionally cautious and must be reviewed because heavy/light distinctions can vary by context and methodology. The statement should not oversimplify the issue."],
  },
  {
    id: "intro-to-ghunnah",
    slug: "intro-to-ghunnah",
    name: "Introduction to Ghunnah",
    arabicName: "غنة",
    category: "Foundations",
    level: "Foundation",
    difficultyScore: 2,
    shortDefinition: "Ghunnah is a nasal sound that is studied in specific Tajweed contexts and is best learned by hearing it rather than guessing from print.",
    detailedExplanation: "Ghunnah is a nasal quality that occurs in certain recognized contexts in Quran recitation. It is associated with specific letters and rule families, especially in the Noon and Meem areas. Because it is a sound phenomenon, it is not sufficient to rely on memorized labels alone. Learners should begin by understanding that ghunnah is a nasal resonance and that its duration and quality are learned with correct demonstration and repetition.",
    whenItOccurs: "It is relevant in certain Noon and Meem rules and in other contexts depending on the selected scholarship and reading tradition.",
    letters: ["ن", "م"],
    pronunciation: "A learner must listen carefully to hear the nasal sound rather than translating it into a simplified English effect.",
    commonMistakes: [
      "Treating ghunnah as a speech habit instead of a Tajweed concept.",
      "Copying a guess about the sound without listening to a qualified reciter.",
    ],
    memoryTip: "If you hear a nasal quality in a rule family, check whether the rule involves ghunnah in context before deciding the full treatment.",
    prerequisites: ["makharij-al-huruf"],
    relatedRules: ["ikhfa", "idgham-with-ghunnah", "ikhfa-shafawi"],
    quranExamples: [],
    practiceQuestions: [
      "Why is ghunnah best learned by ear?",
      "What is the relationship between ghunnah and Noon/Meem contexts?",
    ],
    faq: [
      { question: "Is ghunnah a separate rule?", answer: "It is a sound quality that becomes relevant within specific rule contexts and should not be separated from the larger rule family." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This is a careful introductory summary. The exact contexts and durations should be reviewed with a qualified source before publication as a final claim."],
  },
  {
    id: "noon-sakinah",
    slug: "noon-sakinah",
    name: "Noon Sakinah",
    arabicName: "النون الساكنة",
    category: "Noon and Tanween",
    level: "Essential",
    difficultyScore: 2,
    shortDefinition: "Noon Sakinah is the noon letter when it carries no vowel sign. It is the starting point for the Noon and Tanween rule family.",
    detailedExplanation: "This rule family begins by identifying the Noon letter in a saakin condition. The learner must then look at the following letter to decide whether the sound is clear, merged, concealed, or changed. Noon Sakinah is not just the letter itself; it is the situation in which the letter has no vowel and is governed by one of the recognized rule families. The student's understanding should be based on the next letter, the particular case, and the chosen teaching method.",
    whenItOccurs: "It occurs when the Noon letter is written with a sukoon or when the reciter encounters a Noon letter in a saakin state in context.",
    letters: ["ن"],
    pronunciation: "The learner should identify the condition first and then practice the proper sound treatment with a verified demonstration rather than relying on a written label alone.",
    commonMistakes: [
      "Failing to identify the Noon as saakin before applying a rule.",
      "Thinking every Noon saakin case is the same.",
    ],
    memoryTip: "Noon Sakinah is the trigger: identify the letter and the following letter, then choose the rule family.",
    prerequisites: ["basic-arabic-pronunciation", "makharij-al-huruf"],
    relatedRules: ["tanween", "izhar", "idgham", "iqlab", "ikhfa"],
    quranExamples: [],
    practiceQuestions: [
      "What must be present before we identify the Noon Sakinah family?",
      "Why is the following letter important in this family?",
    ],
    faq: [
      { question: "Is Noon Sakinah always the same sound?", answer: "No. The rule depends on the following letter and the specific case applied in the selected teaching tradition." },
    ],
    sources: ["tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Tajweed Rules Reference"],
    reviewNotes: ["This is a standard explanation and should be reviewed for exact terminology before final publication."],
  },
  {
    id: "tanween",
    slug: "tanween",
    name: "Tanween",
    arabicName: "التنوين",
    category: "Noon and Tanween",
    level: "Essential",
    difficultyScore: 2,
    shortDefinition: "Tanween is the doubled vowel sound at the end of a word, and it is treated under the same Noon and Tanween rule family.",
    detailedExplanation: "Tanween is a term for the doubled vowel sound represented in writing by the symbols of fatḥatayn, dammatayn, and kasratayn. It is studied in the same family as Noon Sakinah because the same principles of clear reading, merging, concealment, and change can apply when the sound is followed by a specific letter. The key is to identify the sound pattern and then recognize the following letter to determine which rule applies.",
    whenItOccurs: "It occurs when a word ends with a doubled vowel sound or when the word ending has the tanween sign in the text.",
    letters: ["ن", "ت", "م", "ك"],
    pronunciation: "The learner should hear the tanween sound as an ending pattern and then analyze the next letter with a qualified demonstration.",
    commonMistakes: [
      "Ignoring the double vowel sign and treating the ending as if it were a simple single vowel.",
      "Assuming tanween is unrelated to the Noon Sakinah family.",
    ],
    memoryTip: "Tanween behaves like a Noon Sakinah in the rule family: identify the ending pattern and the following letter.",
    prerequisites: ["noon-sakinah", "basic-arabic-pronunciation"],
    relatedRules: ["izhar", "idgham", "ikhfa", "iqlab"],
    quranExamples: [],
    practiceQuestions: [
      "How is Tanween related to Noon Sakinah?",
      "Why does the following letter matter in Tanween cases?",
    ],
    faq: [
      { question: "Does Tanween always receive the same treatment?", answer: "No. The exact case depends on the following letter and the selected teaching tradition." },
    ],
    sources: ["tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Tajweed Rules Reference"],
    reviewNotes: ["This is standard learning content but needs review before being called final because exact terminology may vary across methodologies."],
  },
  {
    id: "izhar",
    slug: "izhar",
    name: "Izhar",
    arabicName: "الإظهار",
    category: "Noon and Tanween",
    level: "Essential",
    difficultyScore: 2,
    shortDefinition: "Izhar is the clear pronunciation of Noon Sakinah or Tanween when the following letter is one of the letters of clear pronunciation.",
    detailedExplanation: "In the Noon Sakinah and Tanween family, Izhar is the case in which the Noon or tanween sound remains clear and is not merged, concealed, or changed. The condition depends on the following letter. This rule is best learned by identifying the trigger first and then listening to a reliable demonstration of what clear pronunciation sounds like. Different methodologies may group or classify the letters differently; therefore, this should remain careful and review-sensitive.",
    whenItOccurs: "It occurs when Noon Sakinah or Tanween is followed by a letter that belongs to the clear-reading case in the selected teaching system.",
    letters: ["ء", "ه", "ع", "ح", "غ", "خ"],
    pronunciation: "The sound stays clear, without merging or concealment, and should be reproduced with a precise opening of the sound according to qualified instruction.",
    commonMistakes: [
      "Turning a clear Noon into an Idgham or Ikhfa case by mistake.",
      "Adding an artificial sound or pause where none belongs.",
    ],
    memoryTip: "If the following letter is not in the merging or concealment set in your learning system, begin with the clear-reading case.",
    prerequisites: ["noon-sakinah", "tanween"],
    relatedRules: ["idgham", "ikhfa", "iqlab"],
    quranExamples: [],
    practiceQuestions: [
      "How can the learner recognize Izhar before choosing another rule?",
      "What is the difference between Izhar and Idgham?",
    ],
    faq: [{ question: "Is Izhar only a name, or does it affect the sound?", answer: "It affects the sound and the learner should hear the difference from a verified reciter." }],
    sources: ["tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Tajweed Rules Reference"],
    reviewNotes: ["The exact letter set and terminology must be checked against a recognized source before this is accepted as final."],
  },
  {
    id: "idgham",
    slug: "idgham",
    name: "Idgham",
    arabicName: "الإدغام",
    category: "Noon and Tanween",
    level: "Essential",
    difficultyScore: 3,
    shortDefinition: "Idgham is the merging of Noon Sakinah or Tanween into a following letter in the cases assigned to this rule.",
    detailedExplanation: "This is one of the main Noon and Tanween families. In the relevant cases, the sound is merged with the following letter rather than remaining fully clear. The category has subcases and variations, and it is important not to reduce all Idgham cases to the same sound treatment. The learner must first identify the Noon or tanween, then the following letter, and then learn the correct subcase with a qualified reciter. This is a rule family that is best learned step by step rather than all at once.",
    whenItOccurs: "It occurs when a Noon Sakinah or Tanween is followed by a letter assigned to the merging case in the selected methodology.",
    letters: ["ي", "ر", "م", "ل", "و", "ن"],
    pronunciation: "The sound is merged according to the relevant subcase, with voice and timing following the qualified demonstration rather than the learner's guess.",
    commonMistakes: [
      "Undoing the merge by reading the sound too clearly.",
      "Applying Idgham to every Noon Sakinah case regardless of the next letter.",
    ],
    memoryTip: "If the rule is a merge, the sound must be identified as the next-letter trigger determines the case.",
    prerequisites: ["noon-sakinah", "tanween"],
    relatedRules: ["izhar", "ikhfa", "iqlab", "idgham-with-ghunnah", "idgham-without-ghunnah"],
    quranExamples: [],
    practiceQuestions: [
      "What distinguishes Idgham from Izhar?",
      "Why should learners not treat all merging patterns as the same?",
    ],
    faq: [
      { question: "Can Idgham be recognized visually?", answer: "The visual trigger helps guide recognition, but the actual sound still needs to be heard and corrected with a qualified reciter." },
    ],
    sources: ["tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Tajweed Rules Reference"],
    reviewNotes: ["This is a clear educational overview, but the exact classified subcases should be reviewed before being treated as final production content."],
  },
  {
    id: "idgham-with-ghunnah",
    slug: "idgham-with-ghunnah",
    name: "Idgham with Ghunnah",
    arabicName: "إدغام مع غنة",
    category: "Noon and Tanween",
    level: "Essential",
    difficultyScore: 3,
    shortDefinition: "A form of Idgham in which the Noon Sakinah or Tanween is merged with the following letter while ghunnah is applied.",
    detailedExplanation: "This is a subcase within the wider Idgham family, distinguished by the presence of ghunnah. The learner should identify the Noon Sakinah or Tanween and then detect the following letter in the assigned case. The merged sound is produced together, but the nasal quality is retained in a controlled way. This requires careful listening and is not suitable for a simplistic written-only explanation.",
    whenItOccurs: "It occurs in the relevant letter and sound conditions assigned to this subcase within the selected methodology.",
    letters: ["م", "ن", "ي", "و"],
    pronunciation: "The merge happens while the nasal quality is heard and controlled according to the qualified demonstration for the selected tradition.",
    commonMistakes: [
      "Forgetting the nasal element.",
      "Confusing this subcase with the non-ghunnah form.",
    ],
    memoryTip: "When you see a merge and hear a nasal quality, check the assigned subcase rather than assuming all merges behave the same way.",
    prerequisites: ["idgham", "intro-to-ghunnah"],
    relatedRules: ["idgham-without-ghunnah", "idgham", "ikhfa"],
    quranExamples: [],
    practiceQuestions: [
      "What makes this Idgham subcase different from other merge cases?",
      "Why is a nasal quality essential here?",
    ],
    faq: [
      { question: "Does every merge automatically include ghunnah?", answer: "No. This is a subcase within the family and must be distinguished from the non-ghunnah type." },
    ],
    sources: ["tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Tajweed Rules Reference"],
    reviewNotes: ["This content reflects a standard pedagogical distinction, but final wording and the exact letter set should be checked against a respected source before publication."],
  },
  {
    id: "idgham-without-ghunnah",
    slug: "idgham-without-ghunnah",
    name: "Idgham without Ghunnah",
    arabicName: "إدغام بلا غنة",
    category: "Noon and Tanween",
    level: "Essential",
    difficultyScore: 3,
    shortDefinition: "A merge case in which the Noon Sakinah or Tanween is absorbed without the nasal quality of ghunnah.",
    detailedExplanation: "In certain cases, the sound is merged without the ghunnah quality. This distinction is important because one subcase can sound like a merge but still differ in nasal quality. Learners should not rely on a broad label like 'merge' alone. They need to identify the specific case and then listen to the result under qualified guidance.",
    whenItOccurs: "It occurs in the specific letter condition assigned to this subcase in the selected methodology.",
    letters: ["ل", "ر"],
    pronunciation: "The merge occurs without introducing the nasal quality associated with ghunnah, and the learner should use a precise demonstration to confirm the exact sound.",
    commonMistakes: [
      "Adding ghunnah to every Idgham case.",
      "Confusing this with the ghunnah version because the sound is merged.",
    ],
    memoryTip: "Remember: merge does not always mean ghunnah.",
    prerequisites: ["idgham", "intro-to-ghunnah"],
    relatedRules: ["idgham-with-ghunnah", "idgham", "izhar"],
    quranExamples: [],
    practiceQuestions: [
      "What is the main difference between the two Idgham subcases?",
      "Why is the nasal component so important here?",
    ],
    faq: [
      { question: "Is Idgham without ghunnah a separate main rule?", answer: "It is a subcase of Idgham, not a separate top-level rule family." },
    ],
    sources: ["tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Tajweed Rules Reference"],
    reviewNotes: ["This is pedagogically useful and consistent with the standard family structure, but the exact letter groupings and wording should be verified before final release."],
  },
  {
    id: "iqlab",
    slug: "iqlab",
    name: "Iqlab",
    arabicName: "الإقلاب",
    category: "Noon and Tanween",
    level: "Essential",
    difficultyScore: 3,
    shortDefinition: "Iqlab is the change of Noon Sakinah or Tanween to the sound of a following letter in its assigned case.",
    detailedExplanation: "Iqlab is a specific rule within the Noon and Tanween family in which the sound is transformed before the following letter. The learner must identify the Noon Sakinah or tanween, detect the proper trigger, and then recognize the letter and movement in a qualified demonstration. The sound is not simply a theory; it is a practical change that should be heard, listened to, and repeated under correct guidance.",
    whenItOccurs: "It occurs when Noon Sakinah or Tanween is followed by the specific letter assigned to Iqlab in the selected methodology.",
    letters: ["ب"],
    pronunciation: "The sound changes toward the following letter in the taught pattern; the learner should verify the exact result with a qualified reciter and not rely on a written approximation alone.",
    commonMistakes: [
      "Treating Iqlab as a general substitute for other Noon cases.",
      "Skipping the required listening and practice steps.",
    ],
    memoryTip: "Iqlab is a specific change; it is not simply 'any time Noon is followed by a letter that feels similar'.",
    prerequisites: ["noon-sakinah", "tanween"],
    relatedRules: ["izhar", "idgham", "ikhfa"],
    quranExamples: [],
    practiceQuestions: [
      "What is the main trigger for Iqlab?",
      "How can a learner distinguish Iqlab from Ikhfa and Idgham?",
    ],
    faq: [
      { question: "Is Iqlab common in everyday reading?", answer: "It is a recognized case in the Noon and Tanween family, but it should be studied with care because the sound changes are not a matter of guesswork." },
    ],
    sources: ["tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Tajweed Rules Reference"],
    reviewNotes: ["This explanation is serviceable for learner orientation, but the exact trigger and sound treatment should be reviewed against a recognized source before final publication."],
  },
  {
    id: "ikhfa",
    slug: "ikhfa",
    name: "Ikhfa",
    arabicName: "الإخفاء",
    category: "Noon and Tanween",
    level: "Essential",
    difficultyScore: 3,
    shortDefinition: "Ikhfa is the partial concealment of Noon Sakinah or Tanween when the following letter belongs to the concealment set in the selected teaching system.",
    detailedExplanation: "Ikhfa is one of the major Noon and Tanween families. The sound is not fully clear and not fully merged; it is a middle treatment that is heard and practiced, not simply described in print. The learner begins by identifying Noon Sakinah or Tanween, then the following letter, and then the relevant rule according to the selected methodology. The exact sound quality and length of the nasal resonance depend on the demonstration and curriculum used.",
    whenItOccurs: "It occurs when Noon Sakinah or Tanween is followed by one of the letters assigned to Ikhfa.",
    letters: ["ت", "ث", "ج", "د", "ذ", "ز", "س", "ش", "ص", "ض", "ط", "ظ", "ف", "ق", "ك"],
    pronunciation: "The sound is between clear and merged and should be heard from a qualified demonstration with controlled nasalization and timing.",
    commonMistakes: [
      "Reading the Noon as completely clear or completely merged.",
      "Assuming every concealment case is the same without hearing the demonstration.",
    ],
    memoryTip: "If the letter is in the concealment family, the sound should not be fully pronounced as Izhar nor fully merged as Idgham.",
    prerequisites: ["noon-sakinah", "tanween", "intro-to-ghunnah"],
    relatedRules: ["izhar", "idgham", "iqlab"],
    quranExamples: [],
    practiceQuestions: [
      "How does Ikhfa differ from Izhar and Idgham?",
      "Why is the following letter so important here?",
    ],
    faq: [
      { question: "Is Ikhfa always the same sound?", answer: "The treatment is a family category. The exact sound quality is learned through a reliable demonstration and should not be guessed from text alone." },
    ],
    sources: ["tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Tajweed Rules Reference"],
    reviewNotes: ["This page is a good learner-facing summary, but the exact letter set and nasal timing should be reviewed against the adopted source before final publishing."],
  },
  {
    id: "meem-sakinah",
    slug: "meem-sakinah",
    name: "Meem Sakinah",
    arabicName: "الميم الساكنة",
    category: "Meem Sakinah",
    level: "Essential",
    difficultyScore: 2,
    shortDefinition: "Meem Sakinah is a Meem letter without a vowel, and it is studied in the same way as Noon Sakinah but with its own rule family.",
    detailedExplanation: "Meem Sakinah is the Meem letter in a saakin state. It is followed by a special set of rules commonly taught as Ikhfa Shafawi, Idgham Shafawi, and Izhar Shafawi. This family is not a separate general rule for every Meem; the condition depends on the following letter and the rule assigned in the curriculum. The learner should begin by identifying whether the Meem is saakin, then determine the next letter and the sound treatment.",
    whenItOccurs: "It occurs when a Meem letter carries sukoon and is followed by a letter that triggers one of the Meem-case rules.",
    letters: ["م"],
    pronunciation: "The learner should focus on the sound of the Meem in a saakin state and the relationship to the following letter, using accurate demonstrations.",
    commonMistakes: [
      "Ignoring the Meem's sukoon and treating it like an ordinary Meem.",
      "Applying a Noon rule to a Meem case.",
    ],
    memoryTip: "A Meem saakin is a trigger. The next letter decides which of the three Meem rules applies.",
    prerequisites: ["basic-arabic-pronunciation", "makharij-al-huruf"],
    relatedRules: ["ikhfa-shafawi", "idgham-shafawi", "izhar-shafawi"],
    quranExamples: [],
    practiceQuestions: [
      "How do we recognize Meem Sakinah before looking at the next letter?",
      "Why is the next letter essential in the Meem family?",
    ],
    faq: [
      { question: "Is the Meem family independent of Noon Sakinah?", answer: "Yes, it is its own family, though the same general teaching logic of condition, trigger, and listening applies." },
    ],
    sources: ["tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Tajweed Rules Reference"],
    reviewNotes: ["This is a good summary but should be reviewed to ensure the selection of rule names and the teaching sequence match the adopted methodology."],
  },
  {
    id: "ikhfa-shafawi",
    slug: "ikhfa-shafawi",
    name: "Ikhfa Shafawi",
    arabicName: "الإخفاء الشفوي",
    category: "Meem Sakinah",
    level: "Essential",
    difficultyScore: 3,
    shortDefinition: "Ikhfa Shafawi is a Meem Sakinah case in which the sound is partially concealed with the lips involved in the transition.",
    detailedExplanation: "This is the Meem-family concealment case associated with the lips. The learner identifies the Meem saakin and the following letter, then learns the sound treatment through a qualified demonstration. This is not merely a matter of a visual pattern or a single label; it involves a specific sound outcome. The articulation and the collapsed nature of the sound are best learned by ear.",
    whenItOccurs: "It occurs when Meem Sakinah is followed by the letter or condition assigned to the concealment case in the selected methodology.",
    letters: ["ب"],
    pronunciation: "The sound is hidden and shaped with the lips, with ghunnah or related nasal handling depending on the selected description and demonstration.",
    commonMistakes: [
      "Treating the lips alone as a full explanation.",
      "Confusing Ikhfa Shafawi with the more general Ikhfa of Noon Sakinah.",
    ],
    memoryTip: "In the Meem family, start with the letter and the lips; a sound treatment is not decided by name alone.",
    prerequisites: ["meem-sakinah", "makharij-al-huruf"],
    relatedRules: ["idgham-shafawi", "izhar-shafawi", "meem-sakinah"],
    quranExamples: [],
    practiceQuestions: [
      "What distinguishes Meem Sakinah from Noon Sakinah?",
      "Why is the lip articulation important here?",
    ],
    faq: [
      { question: "Is the sound the same as general Ikhfa?", answer: "No. The Meem-family case is separate and should be regarded as its own teaching category." },
    ],
    sources: ["tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Tajweed Rules Reference"],
    reviewNotes: ["The exact definition and the letter classification should be checked against the selected methodology before production."],
  },
  {
    id: "idgham-shafawi",
    slug: "idgham-shafawi",
    name: "Idgham Shafawi",
    arabicName: "الإدغام الشفوي",
    category: "Meem Sakinah",
    level: "Essential",
    difficultyScore: 3,
    shortDefinition: "Idgham Shafawi is the Meem Sakinah case in which the Meem is merged with the next sound in the manner assigned by the teaching system.",
    detailedExplanation: "This is one of the three Meem Sakinah cases. The learner must identify the Meem in a saakin condition and then decide whether the sound is concealed, merged, or clear based on the next letter. The emphasis here is not on reading a label but on recognizing and hearing the actual sound treatment. The exact articulation and sound effect should be verified by a skilled teacher or reciter.",
    whenItOccurs: "It occurs when Meem Sakinah is followed by the letter or condition assigned to the merging case in the selected methodology.",
    letters: ["م"],
    pronunciation: "The sound is merged in the assigned case, with the correct production and timing recognized through audio-based learning.",
    commonMistakes: [
      "Confusing the Meem-family merge with the Noon-family merge.",
      "Thinking every Meem saakin sound is the same.",
    ],
    memoryTip: "For the Meem family, identify Meem Sakinah first, then the next letter, and then the case. Do not rely on memorized labels alone.",
    prerequisites: ["meem-sakinah", "makharij-al-huruf"],
    relatedRules: ["ikhfa-shafawi", "izhar-shafawi", "idgham"],
    quranExamples: [],
    practiceQuestions: [
      "How does Idgham Shafawi differ from Ikhfa Shafawi?",
      "What is the first step when a Learner sees Meem Sakinah?",
    ],
    faq: [
      { question: "Is the Meem family a separate branch of Tajweed?", answer: "Yes. It is a separate family with its own conditions and sound outcomes even though the same general recognition logic applies." },
    ],
    sources: ["tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Tajweed Rules Reference"],
    reviewNotes: ["This is a valid overview, but the exact letters and sound description should be checked with a qualified source before final publication."],
  },
  {
    id: "izhar-shafawi",
    slug: "izhar-shafawi",
    name: "Izhar Shafawi",
    arabicName: "الإظهار الشفوي",
    category: "Meem Sakinah",
    level: "Essential",
    difficultyScore: 3,
    shortDefinition: "Izhar Shafawi is the Meem Sakinah case in which the sound remains clear and is not concealed or merged.",
    detailedExplanation: "This is the clear-reading Meem case. After identifying Meem Sakinah, the learner notices the next letter and the condition assigned to the clear case. The sound is not merged or concealed. This makes the case easier to recognize by condition, but the sound must still be confirmed with a qualified demonstration. The learner should not assume that a rule can be fully learnt from a brief written label alone.",
    whenItOccurs: "It occurs when the Meem saakin condition does not lead to the assigned concealment or merge and follows the clear-reading case.",
    letters: [],
    pronunciation: "The Meem sound remains clear with proper articulation and is not forced into a merge or concealment pattern.",
    commonMistakes: [
      "Treating every Meem sound as if the same rule applies.",
      "Forgetting the Meem's saakin status before identifying the case.",
    ],
    memoryTip: "When the Meem is saakin and the case is not one of the assigned special cases, begin with the clear treatment.",
    prerequisites: ["meem-sakinah", "makharij-al-huruf"],
    relatedRules: ["ikhfa-shafawi", "idgham-shafawi", "izhar"],
    quranExamples: [],
    practiceQuestions: [
      "What defines the clear Meem case?",
      "How can a learner avoid mixing Meem-family rules together?",
    ],
    faq: [
      { question: "Is Izhar Shafawi simply the absence of the other rules?", answer: "It is the clear-reading case in the Meem family, but it still needs proper sound guidance rather than a purely negative definition." },
    ],
    sources: ["tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Tajweed Rules Reference"],
    reviewNotes: ["The learner-facing explanation is acceptable, but the exact classification and letter conditions should be checked before the site presents the content as approved."],
  },
  {
    id: "qalqalah-letters",
    slug: "qalqalah-letters",
    name: "Qalqalah Letters",
    arabicName: "حروف القلقلة",
    category: "Qalqalah",
    level: "Essential",
    difficultyScore: 2,
    shortDefinition: "Qalqalah letters are the letters that are taught with a bouncing or echoing release when they are saakin.",
    detailedExplanation: "Qalqalah is associated with a set of letters that are taught in the Tajweed tradition, and they are recognized by the fact that the letter's articulation point is emphasized when the letter is saakin. A learner should not simply memorize a list without hearing the manner of release. The sound is a feature of a specific letter when it is at rest, and the context matters. This is one of the reasons why the learner should combine a written rule with listening and teacher correction.",
    whenItOccurs: "It appears when one of the Qalqalah letters is saakin and not given a separate changed treatment in a special context.",
    letters: ["ق", "ط", "ب", "ج", "د"],
    pronunciation: "The letter is released at its articulation point with a controlled bounce or echoing effect, and it should be confirmed by a qualified demonstration.",
    commonMistakes: [
      "Adding a full vowel after the letter.",
      "Thinking every letter with a strong articulation point has Qalqalah.",
    ],
    memoryTip: "The letter set is the first step; the saakin condition is the second step.",
    prerequisites: ["makharij-al-huruf", "sifaat-al-huruf"],
    relatedRules: ["qalqalah-when-sakin", "qalqalah-sughra", "qalqalah-kubra"],
    quranExamples: [],
    practiceQuestions: [
      "What is the first thing to check in Qalqalah?",
      "Why should the learner not reduce Qalqalah to a simple visual label?",
    ],
    faq: [
      { question: "Is Qalqalah a separate letter quality?", answer: "It is a letter-based feature associated with a saakin condition, and the exact way it is taught depends on the adopted methodology." },
    ],
    sources: ["recite-with-love-curriculum", "tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum", "Tajweed Rules Reference"],
    reviewNotes: ["This is a standard overview, but the exact letter set and pronunciation distinctions should be reviewed before final publication."],
  },
  {
    id: "qalqalah-when-sakin",
    slug: "qalqalah-when-sakin",
    name: "Qalqalah when letters are sakin",
    arabicName: "القَلْقَلَةُ في الحرف الساكن",
    category: "Qalqalah",
    level: "Essential",
    difficultyScore: 2,
    shortDefinition: "A Qalqalah letter should be recognized when it is saakin, because the sound is then released with the characteristic jump or echoing effect.",
    detailedExplanation: "The saakin condition is central to Qalqalah. If the letter is not saakin, the rule may not apply in the same way. The learner should therefore separate the letter inventory from the condition. Once the saakin condition is identified, the reciter can reflect on the release of the letter and the relation to the selected teaching method. This is an example of a rule that needs both recognition and listening.",
    whenItOccurs: "It occurs when a Qalqalah letter carries sukoon in the relevant context.",
    letters: ["ق", "ط", "ب", "ج", "د"],
    pronunciation: "The letter's release should be clear and controlled without adding a secondary vowel sound.",
    commonMistakes: [
      "Ignoring the saakin state and treating the letter as though it were mutaharrik.",
      "Adding an extra vowel or overemphasizing the sound in a way that changes the letter's original release.",
    ],
    memoryTip: "Letter set first, then vowel state: that is the order of recognition.",
    prerequisites: ["qalqalah-letters"],
    relatedRules: ["qalqalah-sughra", "qalqalah-kubra", "waqf"],
    quranExamples: [],
    practiceQuestions: [
      "Why is the saakin state essential for Qalqalah?",
      "What happens when a Qalqalah letter is not saakin?",
    ],
    faq: [
      { question: "Does the sound always feel the same in every Qalqalah word?", answer: "The basic letter-based principle is constant, but the exact effect is heard in context and should be confirmed with a qualified reciter." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This is structurally sound, but the exact distinction between small and large Qalqalah should be reviewed before the page is published as a final teaching resource."],
  },
  {
    id: "qalqalah-sughra",
    slug: "qalqalah-sughra",
    name: "Qalqalah Sughra",
    arabicName: "القلقلة الصغرى",
    category: "Qalqalah",
    level: "Essential",
    difficultyScore: 3,
    shortDefinition: "Qalqalah Sughra is the smaller or less emphasized Qalqalah form that occurs in some contexts when the letter is saakin in a word or at a pause.",
    detailedExplanation: "Qalqalah is often taught in a divided way depending on the context and the selected terminology. The small form is a contextual classification that appears in a rule system being taught in a structured way, and it should not be treated as a casual label. The learner should focus on the selected curriculum and not assume that the exact distinction of Sughra and Kubra is the same in all manuals. Without a qualified source, the terminology must be treated carefully.",
    whenItOccurs: "It occurs in the positions assigned to the smaller Qalqalah form in the selected methodology.",
    letters: ["ق", "ط", "ب", "ج", "د"],
    pronunciation: "The letter is released with the characteristic Qalqalah effect in a way that is taught through demonstration and careful listening.",
    commonMistakes: [
      "Assuming Qalqalah Sughra and Qalqalah Kubra are interchangeable labels.",
      "Using a classification without verifying the source.",
    ],
    memoryTip: "The term is contextual; the actual sound should be learned from a trusted reciter, not from the label alone.",
    prerequisites: ["qalqalah-when-sakin"],
    relatedRules: ["qalqalah-kubra", "waqf"],
    quranExamples: [],
    practiceQuestions: [
      "What does the word 'sughra' add to the learning of Qalqalah?",
      "Why should the learner avoid assuming one terminology system matches all sources?",
    ],
    faq: [
      { question: "Is Qalqalah Sughra a universal rule?", answer: "The category is discussed in some teaching systems and should be handled carefully because terminology and classification can vary by methodology." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This term should be maintained only as a source-sensitive category. It requires scholar review before finalizing exact content."],
  },
  {
    id: "qalqalah-kubra",
    slug: "qalqalah-kubra",
    name: "Qalqalah Kubra",
    arabicName: "القلقلة الكبرى",
    category: "Qalqalah",
    level: "Essential",
    difficultyScore: 3,
    shortDefinition: "Qalqalah Kubra is the larger or more emphasized Qalqalah form used in some contextual classifications of the same letter-based property.",
    detailedExplanation: "This is the contextual counterpart to the small form in some classifications. It should only be taught with a source-based explanation because the terminology is not universally identical across all Tajweed traditions and texts. The learner should stay with the curriculum and be explicit that the exact terminology and classification may vary. The core principle remains the Qalqalah letter and the saakin condition; the added category should be treated carefully.",
    whenItOccurs: "It occurs in the position or context assigned to the larger Qalqalah form in the adopted teaching system.",
    letters: ["ق", "ط", "ب", "ج", "د"],
    pronunciation: "The release is heard with the characteristic Qalqalah effect, but only under the contextual classification used by the selected source.",
    commonMistakes: [
      "Assuming one textbook's terminology is universal.",
      "Teaching the classification without source review.",
    ],
    memoryTip: "Do not let the label replace the source. Treat the classification as a reviewed term, not a casual category.",
    prerequisites: ["qalqalah-when-sakin", "qalqalah-sughra"],
    relatedRules: ["qalqalah-sughra", "waqf"],
    quranExamples: [],
    practiceQuestions: [
      "Why should the learner not treat Qalqalah Kubra as a universal, unqualified category?",
      "What is the role of source review here?",
    ],
    faq: [
      { question: "Do all Tajweed sources use the same classification?", answer: "No. Terminology and contextual classification can differ, so the learner should use reviewed curriculum definitions rather than assuming a single universal pattern." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This entry is intentionally careful, but it should remain marked as requiring scholar review until the exact terminology is approved by the selected source."],
  },
  {
    id: "lam-in-allah",
    slug: "lam-in-allah",
    name: "Lam in Allah",
    arabicName: "لام الله",
    category: "Lam and Raa",
    level: "Intermediate",
    difficultyScore: 2,
    shortDefinition: "The Lam in Allah is a common case where the letter Lam is treated according to the special sound quality associated with the word Allah in reading.",
    detailedExplanation: "The word Allah is a common and important case in Tajweed. The Lam in the word Allah is taught in relation to letter quality, heaviness, and lightness, and some curricula discuss it in the broader context of Lam rules. Because the term and treatment may vary with the teaching tradition, the learner should use a consistent educational framework and receive teacher feedback rather than rely on oversimplified memory rules.",
    whenItOccurs: "It appears specifically in the word Allah or in related recitation contexts where Lam is part of the word Allah.",
    letters: ["ل"],
    pronunciation: "The learner must hear the sound and understand whether the Lam is treated as light or heavy in context according to the selected methodology and reciter.",
    commonMistakes: [
      "Reducing the word Allah to a simple visual pattern without hearing the sound.",
      "Treating the Lam in Allah as if it were identical in every recitation context.",
    ],
    memoryTip: "The word Allah is a memorized case in many curricula, but the sound still needs to be heard, not just named.",
    prerequisites: ["heavy-and-light-letters"],
    relatedRules: ["lam-shamsiyyah", "lam-qamariyyah", "taa"],
    quranExamples: [],
    practiceQuestions: [
      "Why is the Lam in Allah treated as a special case?",
      "Why must a learner avoid a purely visual rule for this word?",
    ],
    faq: [
      { question: "Is every Lam in Allah treated the same way?", answer: "The broad classification is recognized in many curricula, but the learner should check the exact pedagogical handling of the term in the adopted teaching system." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This is a conceptually important topic that should be reviewed for precise terminology and teaching alignment before production."],
  },
  {
    id: "lam-shamsiyyah",
    slug: "lam-shamsiyyah",
    name: "Lam Shamsiyyah",
    arabicName: "لام شمسية",
    category: "Lam and Raa",
    level: "Intermediate",
    difficultyScore: 2,
    shortDefinition: "Lam Shamsiyyah is the Lam that is assimilated to the following shamsiyyah letter in the manner taught in the selected curriculum.",
    detailedExplanation: "This is a practical and important part of the Lam family. The learner first identifies the Lam and then the following letter. The case is recognized by the rule family and by the actual sound treatment used in recitation. A learner should not rely on a simplistic label alone; the rule must be heard and repeated under qualified guidance. The exact descriptions vary across teachings, so this content should remain sensitive to the curriculum being used.",
    whenItOccurs: "It occurs when the Lam letter is followed by the relevant solar-letter trigger assigned to the teaching system.",
    letters: ["ل", "ش"],
    pronunciation: "The sound is assimilated or adjusted to the following letter according to the selected methodology; the actual audio demonstration should govern the learner's practice.",
    commonMistakes: [
      "Ignoring the following letter and relying only on the Lam letter itself.",
      "Assuming the same explanation applies to every Lam family case.",
    ],
    memoryTip: "Lam first, then the next letter. A single letter label is not enough to decide the case.",
    prerequisites: ["lam-in-allah", "heavy-and-light-letters"],
    relatedRules: ["lam-qamariyyah", "lam-in-allah", "sifaat-al-huruf"],
    quranExamples: [],
    practiceQuestions: [
      "What must a learner check before deciding Lam Shamsiyyah?",
      "How is this different from Lam Qamariyyah?",
    ],
    faq: [
      { question: "Does Lam Shamsiyyah always sound the same?", answer: "The broad family is consistent, but the exact sound is learned with listening and teacher feedback rather than by memorizing a shortened rule." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This entry should remain labeled as a curriculum-sensitive topic because the exact teaching language may differ by source."],
  },
  {
    id: "lam-qamariyyah",
    slug: "lam-qamariyyah",
    name: "Lam Qamariyyah",
    arabicName: "لام قمرية",
    category: "Lam and Raa",
    level: "Intermediate",
    difficultyScore: 2,
    shortDefinition: "Lam Qamariyyah is the clear Lam case when the following letter is one of the lunar letters in the selected teaching framework.",
    detailedExplanation: "This is the complementary case to Lam Shamsiyyah in many curricula. The learner identifies the Lam, then the following letter, and then concludes whether the sound is clear or assimilated according to the selected methodology. The rule is not a useless label but a practical guide to production and listening. It is best learned in context and with a qualified reciter.",
    whenItOccurs: "It occurs when the Lam is followed by a letter assigned to the moon-letter grouping in the relevant teaching system.",
    letters: ["ل", "ق"],
    pronunciation: "The sound stays clear and is not absorbed into the following letter in the same way as in the solar-letter case.",
    commonMistakes: [
      "Assuming the Lam case is decided by the word letters alone.",
      "Forgetting the distinction between clear and assimilated cases.",
    ],
    memoryTip: "Lam Qamariyyah is the clear treatment in the Lam family; always check the next letter before deciding.",
    prerequisites: ["lam-shamsiyyah", "heavy-and-light-letters"],
    relatedRules: ["lam-shamsiyyah", "lam-in-allah"],
    quranExamples: [],
    practiceQuestions: [
      "How is Lam Qamariyyah distinguished from Lam Shamsiyyah?",
      "Why does the following letter matter here?",
    ],
    faq: [
      { question: "Can this be memorized without listening?", answer: "You can memorize the identification pattern, but correct production should still be checked by ear and repetition." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This is useful educational material but should remain flagged as source-sensitive because the exact grouping and terminology may differ by methodology."],
  },
  {
    id: "raa-heavy-and-light",
    slug: "raa-heavy-and-light",
    name: "Raa Heavy and Light",
    arabicName: "تفخيم وتفريق الراء",
    category: "Lam and Raa",
    level: "Intermediate",
    difficultyScore: 3,
    shortDefinition: "Raa may be heavy or light according to the conditions of the vowel and the following letter or context, and the learner must not reduce it to a single simple formula.",
    detailedExplanation: "The Raa rule is one of the classic Tajweed topics that often appears in learner materials. It is not enough to say simply that Raa is heavy with fatha and light with kasra, because the rule is shaped by a combination of letter quality, the vowel signs around it, and the surrounding context. The reciter should identify the Raa itself and then inspect the vowel, the next letter, and the general sound environment. Since this is an area of careful classification, a learner should always use a verified curriculum and a qualified reciter's demonstration.",
    whenItOccurs: "It occurs whenever the Raa letter is pronounced in a context that triggers the heavy or light treatment in the selected teaching system.",
    letters: ["ر"],
    pronunciation: "The sound should be heard in a context-sensitive way rather than reduced to an English rule or a single vowel sign formula.",
    commonMistakes: [
      "Reducing the whole rule to a simplistic pattern." ,
      "Ignoring the surrounding letters and context.",
    ],
    memoryTip: "Raa is a sound-quality case, not a single mechanical formula. Listen, then identify the conditions.",
    prerequisites: ["heavy-and-light-letters", "sifaat-al-huruf"],
    relatedRules: ["heavy-and-light-letters", "tafkhim", "tarqiq"],
    quranExamples: [],
    practiceQuestions: [
      "What makes Raa more than a visual memorization rule?",
      "Why is a learner warned against a simplistic formula?",
    ],
    faq: [
      { question: "Is the rule always decided by one vowel sign?", answer: "No. It is context-sensitive and should be taught with careful conditions and sound guidance." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This explanation is intentionally careful and should remain marked as review-sensitive because the exact conditions should be checked against a recognized source and curriculum."],
  },
  {
    id: "madd-tabii",
    slug: "madd-tabii",
    name: "Madd Tabii",
    arabicName: "المد الطبيعي",
    category: "Madd and lengthening",
    level: "Intermediate",
    difficultyScore: 2,
    shortDefinition: "Madd Tabii is the natural elongation of an alif, ya, or waw when it is followed by a vowel and not by a specific Madd cause or stopping issue.",
    detailedExplanation: "Madd is the family of lengthening rules in Tajweed, and Madd Tabii is the most basic category. In many teaching systems, it is the natural elongation that occurs when a letter of Madd is followed by a vowel sign and the word is read without an additional cause. The learner should begin with this case because the entire Madd system is built on understanding what is natural lengthening and what changes the length in other categories. Sound and timing must be checked by listening.",
    whenItOccurs: "It occurs when the letter of Madd is followed by a vowel and there is no additional special cause such as a Hamzah, a stopping condition, or a separate Madd classification in the adopted system.",
    letters: ["ا", "ي", "و"],
    pronunciation: "The sound is lengthened in the natural pattern and should be practiced under qualified guidance; the precise timing is not to be guessed from the written label alone.",
    commonMistakes: [
      "Assuming all Madd has the same length.",
      "Forgetting the basic vowel-based condition before moving to more advanced Madd categories.",
    ],
    memoryTip: "Begin with the natural Madd case: if the Madd letter is present and there is a vowel after it, the learner should identify the natural lengthening before moving to the advanced cases.",
    prerequisites: ["basic-arabic-pronunciation"],
    relatedRules: ["madd-badal", "madd-lin", "madd-arid-li-sukun", "madd-wajib-muttasil"],
    quranExamples: [],
    practiceQuestions: [
      "What is the difference between natural Madd and other Madd categories?",
      "Why is Madd Tabii a starting point for the Madd system?",
    ],
    faq: [
      { question: "Does Madd Tabii mean all lengthening in the Quran?", answer: "No. Madd Tabii is a foundational category within the larger Madd system and does not cover every lengthening case." },
    ],
    sources: ["tajweed-rules-reference"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Tajweed Rules Reference"],
    reviewNotes: ["This is a broad educational definition and should be reviewed for exact terminology and classifications before publication."],
  },
  {
    id: "waqf",
    slug: "waqf",
    name: "Waqf",
    arabicName: "الوقف",
    category: "Waqf and Ibtida",
    level: "Intermediate",
    difficultyScore: 2,
    shortDefinition: "Waqf is the stopping point in recitation; it is a distinct topic from the sound-treatment rules, and it affects how a reader ends a phrase or unit.",
    detailedExplanation: "Waqf is the act of stopping in recitation, and it is separate from the rule family of Noon or Meem. It is taught through stopping concepts, symbols, and the effect that pausing has on the final sound and on the timing of Madd and other cases. A learner should not confuse a stop with a rule of sound treatment; they are different topics. The correct use of waqf is learned in practice by studying stop signs and listening to a qualified reciter or teacher.",
    whenItOccurs: "It occurs whenever a reciter chooses to stop at the end of a phrase, verse, or other reading unit.",
    letters: [],
    pronunciation: "The final sound is shaped by the stop itself and may be different from the same sound in running recitation, especially in cases involving Madd and pausing.",
    commonMistakes: [
      "Confusing a stop with a letter rule.",
      "Stopping without considering the relevant sign or the effect on the ending sound.",
    ],
    memoryTip: "Waqf is about where the reciter stops, not which letter rule applies to the middle of a word.",
    prerequisites: ["basic-arabic-pronunciation"],
    relatedRules: ["ibtida", "madd-arid-li-sukun", "major-stopping-concepts"],
    quranExamples: [],
    practiceQuestions: [
      "Why is Waqf distinct from a letter rule?",
      "How can stopping affect pronunciation in a recited passage?",
    ],
    faq: [
      { question: "Can stopping change the sound?", answer: "Yes, pausing can affect the ending sound and the timing of related Madd and other recitation features, which is why waqf is a separate discipline." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This is a carefully phrased general explanation, but the exact stopping categories and symbols should be reviewed before final publishing."],
  },
  {
    id: "ibtida",
    slug: "ibtida",
    name: "Ibtida",
    arabicName: "الابتداء",
    category: "Waqf and Ibtida",
    level: "Intermediate",
    difficultyScore: 2,
    shortDefinition: "Ibtida is beginning or resuming recitation after a stop, and it requires awareness of sound, context, and the selected reading discipline.",
    detailedExplanation: "Ibtida is the start of a new recitation unit after a pause. The reader should continue with careful sound, proper articulation, and a clear understanding of where the new unit begins. It is not simply the act of starting from the next word; it is a practical decision that can affect how a reciter joins or restarts the sound. A learner should study it in the context of waqf and stop-signs, particularly when a stop changes how a phrase is continued.",
    whenItOccurs: "It occurs after a stop, when a reciter begins again or starts a new segment of reading.",
    letters: [],
    pronunciation: "The learner should begin with clear articulation and awareness of how the stop may affect the continuing sound at the new start.",
    commonMistakes: [
      "Ignoring the context of a stop when resuming.",
      "Starting without paying attention to the new sound environment.",
    ],
    memoryTip: "A pause is not the end of the lesson; Ibtida is the beginning of the next careful step.",
    prerequisites: ["waqf"],
    relatedRules: ["waqf", "major-stopping-concepts", "how-to-resume"],
    quranExamples: [],
    practiceQuestions: [
      "Why is starting after a stop a separate skill from the stop itself?",
      "How can context influence a restart?",
    ],
    faq: [
      { question: "If I stop in the middle of a recitation, do I need to restart with a new sound?", answer: "The sound should be restarted in a careful and context-aware way, not mechanically or without attention to the stop and the next segment." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This description is learner-friendly and should be reviewed with the stop-sign tradition before publication."],
  },
  {
    id: "hamzat-al-wasl",
    slug: "hamzat-al-wasl",
    name: "Hamzat al-Wasl",
    arabicName: "همزة الوصل",
    category: "Hamzah",
    level: "Advanced",
    difficultyScore: 3,
    shortDefinition: "Hamzat al-Wasl is the connecting Hamzah used in beginning and joining recitation, and it is taught as a separate topic from Hamzat al-Qat' with careful context.",
    detailedExplanation: "The Hamzah issue belongs to advanced recitation study and should be handled carefully. Hamzat al-Wasl is the joining Hamzah commonly discussed in the context of beginning recitation or joining words, while Hamzat al-Qat' is the stopping Hamzah that is cut off at the end. Learners should not assume the terminologies are interchangeable. The concept should be taught through a trusted source and listening, especially when a learner begins a phrase after a stop or connects one word to another.",
    whenItOccurs: "It is relevant at the beginning of recitation or in situations where the word is joined in a connected reading context.",
    letters: ["ء"],
    pronunciation: "The sound is either connected or separated according to the case and the selected methodology; the learner must confirm the proper sound with a qualified reciter.",
    commonMistakes: [
      "Mixing the joining Hamzah with the stopping Hamzah.",
      "Treating it as a purely visual symbol without hearing the context.",
    ],
    memoryTip: "The first question is whether this is a joining Hamzah or a stopping Hamzah. The answer determines the recitation approach.",
    prerequisites: ["ibtida", "basic-arabic-pronunciation"],
    relatedRules: ["hamzat-al-qat", "waqf"],
    quranExamples: [],
    practiceQuestions: [
      "How does Hamzat al-Wasl differ from Hamzat al-Qat'?",
      "Why is context essential in the study of Hamzah?",
    ],
    faq: [
      { question: "Do all learners need to memorize Hamzah rules early?", answer: "Not early. This is an advanced or context-driven topic and should be studied after the core rule families are stable." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["This is a careful, learner-facing summary, but it should remain review-marked because exact terminology and instructional emphasis vary by source."],
  },
  {
    id: "hamzat-al-qat",
    slug: "hamzat-al-qat",
    name: "Hamzat al-Qat'",
    arabicName: "همزة القطع",
    category: "Hamzah",
    level: "Advanced",
    difficultyScore: 3,
    shortDefinition: "Hamzat al-Qat' is the stopping or cut-off Hamzah, which is taught as a different category from Hamzat al-Wasl.",
    detailedExplanation: "This is the complementary Hamzah discussion in which the sound is treated as a stopping or cut-off form rather than as a joining sound. It is essential that learners do not confuse the two Hamzah categories. The terms and the exact teaching approach should remain source-sensitive because this is a specialized topic and not a casual beginner rule.",
    whenItOccurs: "It applies in the situation in which a word or recitation unit ends or is stopped with the relevant Hamzah treatment.",
    letters: ["ء"],
    pronunciation: "The sound is heard as a stopping form and not as a joining form; the exact pronunciation should be confirmed with qualified instruction.",
    commonMistakes: [
      "Using the joining Hamzah description for the stoppage case.",
      "Treating the distinction as visual rather than contextual.",
    ],
    memoryTip: "The first question is whether the Hamzah is joining or cut-off. That distinction governs the correct practice.",
    prerequisites: ["hamzat-al-wasl", "waqf"],
    relatedRules: ["hamzat-al-wasl", "waqf"],
    quranExamples: [],
    practiceQuestions: [
      "What is the main difference between Hamzat al-Wasl and Hamzat al-Qat'?",
      "Why is the stopping context important?",
    ],
    faq: [
      { question: "Should beginners study Hamzah early?", answer: "Not before the core rule families are stable. It is best positioned after foundational knowledge and a careful understanding of waqf and ibtida." },
    ],
    sources: ["recite-with-love-curriculum"],
    verificationStatus: "needs_review",
    reviewStatus: "REQUIRES REVIEW",
    sourceReferences: ["Beginner and Intermediate Tajweed Curriculum"],
    reviewNotes: ["Good conceptual distinction, but term usage and exact emphasis require review before final publication."],
  },
];

export function getRuleBySlug(slug: string) {
  return tajweedRules.find((rule) => rule.slug === slug);
}

export function getRulesByCategory(category: string) {
  return tajweedRules.filter((rule) => rule.category === category);
}

export function getVerifiedRules() {
  return tajweedRules.filter((rule) => rule.verificationStatus === "verified");
}

export function getReviewRequiredRules() {
  return tajweedRules.filter((rule) => rule.verificationStatus === "needs_review");
}
