import { ArrowRight, BookOpen, CheckCircle2, ChevronDown, CirclePlay, Headphones, Layers3, ShieldCheck, Sparkles, Target, Volume2 } from "lucide-react";
import { Breadcrumbs, Button, Footer, QuranExample, QuizCard, RuleCard, SearchPanel, SiteHeader } from "@/components/ui";

const categories = [
  ["Articulation", "مَخَارِجُ الْحُرُوفِ", "Explore where Arabic letters are articulated and how to approach them carefully."],
  ["Noon and tanween", "النُّونُ السَّاكِنَةُ وَالتَّنْوِينُ", "Study a structured family of rules through recognition, examples, and practice."],
  ["Meem sakinah", "المِيمُ السَّاكِنَةُ", "Build familiarity with the cases learners commonly meet in reading."],
  ["Elongation", "المَدُّ", "Understand how elongation is described and where guided listening matters."],
  ["Stopping and starting", "الْوَقْفُ وَالِابْتِدَاءُ", "Learn to approach pauses and beginnings with attention to context."],
  ["Letter qualities", "صِفَاتُ الْحُرُوفِ", "Notice the qualities that help distinguish and shape letter sounds."],
];
const featuredRules = [
  ["Makharij", "مَخَارِجُ الْحُرُوفِ", "Begin with the places of articulation—the foundation for clear, deliberate reading.", "Foundations"],
  ["Noon Sakinah and Tanween", "النُّونُ السَّاكِنَةُ وَالتَّنْوِينُ", "Learn to recognise the rule family before practising its different cases.", "Essential"],
  ["Meem Sakinah", "المِيمُ السَّاكِنَةُ", "A focused lesson path for identifying and practising meem-related patterns.", "Essential"],
  ["Madd", "المَدُّ", "Study elongation with examples that make the listening target easier to notice.", "Intermediate"],
];
const faqs = [
  ["Can I start if I am completely new to Tajweed?", "Yes. Begin with the Foundations path. It is designed to establish the vocabulary, reading habits, and listening approach needed for later rules."],
  ["Do I need to know Arabic?", "You do not need to speak Arabic to begin studying Tajweed, but you do need an appropriate foundation in reading Arabic script. A teacher can help assess where to start."],
  ["Is reading the explanations enough?", "No. Explanations support understanding, while correct pronunciation is developed through listening, repetition, and feedback from a qualified teacher or reciter."],
  ["How should I use the Quran examples?", "First identify the highlighted feature, then listen to a verified recitation, repeat carefully, and ask a teacher to check what you are hearing and producing."],
];

export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero hero-home"><div className="container hero-grid"><div className="hero-copy"><Breadcrumbs /><p className="eyebrow">Learn Tajweed clearly, step by step</p><h1>Master Tajweed. Read the Quran with <span>confidence.</span></h1><p className="hero-lede">A structured English guide to Tajweed lessons, clear examples, listening guidance, practice exercises, and thoughtful learning resources.</p><div className="hero-actions"><Button>Start Learning</Button><a href="#rules" className="outline-link">Explore Tajweed Rules <ArrowRight size={16} /></a></div><div className="trust-row"><span><ShieldCheck size={17} /> Source-conscious content</span><span><Headphones size={17} /> Built for listening and practice</span></div></div><div className="hero-aside hero-dashboard"><div className="dashboard-top"><span className="eyebrow">Your first step</span><span className="badge">Foundations</span></div><div className="dashboard-arabic" lang="ar" dir="rtl">اقْرَأْ بِتَأَنٍّ</div><div className="dashboard-rule"><div className="rule-icon"><Volume2 size={18} /></div><div><strong>Listen for the difference</strong><small>Explanation · Demonstration · Practice</small></div></div><div className="dashboard-lines"><i /><i /><i /></div></div></div></section>
    <section className="search-section"><div className="container"><SearchPanel /></div></section>
    <section className="section intro-section"><div className="container intro-grid"><div><p className="eyebrow">Why learn Tajweed?</p><h2>Make careful reading a practice you can understand.</h2></div><div><p className="large-copy">Tajweed gives learners a way to study the details of Quranic recitation with greater awareness. This guide breaks those details into manageable lessons, then connects each idea to listening and practice.</p><p className="muted">The website explains concepts theoretically; pronunciation is best developed by hearing a qualified reciter and receiving feedback from a qualified teacher.</p></div></div></section>
    <section className="section tinted" id="learn"><div className="container"><div className="section-heading"><div><p className="eyebrow">Learning path</p><h2>A steady progression</h2></div><a className="text-link" href="#">View the full path <ArrowRight size={14} /></a></div><div className="path-grid"><div className="path-step active"><span className="level-index">01</span><div className="path-icon"><Target size={19} /></div><h3>Foundations</h3><p>Get oriented, build good reading habits, and learn the essential vocabulary.</p></div><div className="path-connector" aria-hidden="true">→</div><div className="path-step"><span className="level-index">02</span><div className="path-icon"><Layers3 size={19} /></div><h3>Essential Rules</h3><p>Recognise the recurring rule families you will meet most often.</p></div><div className="path-connector" aria-hidden="true">→</div><div className="path-step"><span className="level-index">03</span><div className="path-icon"><CirclePlay size={19} /></div><h3>Intermediate Rules</h3><p>Strengthen your ear and apply rules in more varied contexts.</p></div><div className="path-connector" aria-hidden="true">→</div><div className="path-step"><span className="level-index">04</span><div className="path-icon"><Sparkles size={19} /></div><h3>Advanced Rules</h3><p>Explore nuance with consistent practice and teacher guidance.</p></div></div></div></section>
    <section className="section" id="categories"><div className="container"><div className="section-heading"><div><p className="eyebrow">Explore by category</p><h2>Find the idea you are ready for</h2></div><a className="text-link" href="#rules">Browse the library <ArrowRight size={14} /></a></div><div className="category-grid">{categories.map(([title, arabic, description]) => <a className="category-card" href="#rules" key={title}><span className="category-arrow"><ArrowRight size={16} /></span><p className="arabic-sm" lang="ar" dir="rtl">{arabic}</p><h3>{title}</h3><p className="muted">{description}</p></a>)}</div></div></section>
    <section className="section tinted" id="rules"><div className="container"><div className="section-heading"><div><p className="eyebrow">Featured rules</p><h2>Start with a clear next step</h2></div><a className="text-link" href="#">See all Tajweed rules <ArrowRight size={14} /></a></div><div className="rule-grid">{featuredRules.map(([title, arabic, description, level]) => <RuleCard key={title} title={title} arabic={arabic} level={level} description={description} />)}</div></div></section>
    <section className="section how-section"><div className="container"><div className="center-heading"><p className="eyebrow">How it works</p><h2>Turn information into a listening habit.</h2></div><div className="how-grid">{[["01", "Learn", "Read the short explanation and learn the key term."], ["02", "Understand", "Connect the rule to what you already know."], ["03", "Observe examples", "Look at a verified, clearly marked example."], ["04", "Practise", "Listen, repeat, and work through a focused exercise."], ["05", "Review", "Return later and check what your ear now notices."]].map(([number, title, text]) => <div className="how-step" key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
    <section className="section beginner-section"><div className="container beginner-grid"><div className="beginner-art" aria-hidden="true"><BookOpen size={42} /><span>01</span></div><div><p className="eyebrow">Completely new?</p><h2>Start with the Foundations path.</h2><p className="large-copy">You do not need to know every term before you begin. Start with orientation, reading prerequisites, and the habits that make later lessons easier to follow.</p><div className="check-list"><span><CheckCircle2 size={17} /> Understand what each lesson is for</span><span><CheckCircle2 size={17} /> Learn how to use examples actively</span><span><CheckCircle2 size={17} /> Know when to ask a teacher for feedback</span></div><Button variant="secondary">Begin Foundations</Button></div></div></section>
    <section className="section soft" id="practice"><div className="container practice-grid"><div><p className="eyebrow">Practice, not pressure</p><h2>Use short exercises to make progress visible.</h2><p className="large-copy">Quizzes help you check recognition and understanding. Practice activities give you a reason to listen, repeat, and return to a rule over time.</p><a className="text-link" href="#">Explore practice resources <ArrowRight size={14} /></a></div><div className="stacked-cards"><QuranExample /><QuizCard /></div></div></section>
    <section className="section" id="articles"><div className="container"><div className="section-heading"><div><p className="eyebrow">Articles and guides</p><h2>Useful reading for the questions between lessons</h2></div><a className="text-link" href="#">View all articles <ArrowRight size={14} /></a></div><div className="article-grid"><article className="article-card featured-article"><span className="badge">Study guide</span><h3>How to use an online Tajweed guide well</h3><p className="muted">A practical rhythm for combining explanation, listening, repetition, and teacher feedback.</p><a className="text-link" href="#">Read guide <ArrowRight size={14} /></a></article><article className="article-card"><span className="badge">Beginner</span><h3>What should I learn first?</h3><p className="muted">A gentle orientation to the Foundations path and what it is designed to do.</p><a className="text-link" href="#">Read guide <ArrowRight size={14} /></a></article><article className="article-card"><span className="badge">Practice</span><h3>Why listening belongs in every lesson</h3><p className="muted">Understand the role of a demonstrated sound without confusing it with theory alone.</p><a className="text-link" href="#">Read guide <ArrowRight size={14} /></a></article></div></div></section>
    <section className="section faq-section"><div className="container faq-grid"><div><p className="eyebrow">Frequently asked questions</p><h2>A clearer beginning starts with good questions.</h2><p className="muted">If your question is about your individual pronunciation, bring it to a qualified teacher or reciter.</p></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={18} /></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="final-cta"><div className="container final-cta-inner"><div><p className="eyebrow">Your next step can be simple</p><h2>Start Learning Tajweed</h2><p>Begin with one lesson, one sound, and one focused practice.</p></div><Button>Start Learning</Button></div></section>
  </main><Footer /></>;
}
