import { ArrowRight, BookOpen, CheckCircle2, ChevronDown, CirclePlay, Headphones, Layers3, ShieldCheck, Sparkles, Target, Volume2 } from "lucide-react";
import { Breadcrumbs, Button, Footer, QuranExample, QuizCard, SearchPanel, SiteHeader } from "@/components/ui";
import { curriculumAreas } from "@/lib/tajweed/curriculum";
import { tajweedExamples } from "@/lib/tajweed/examples";
import { tajweedRules } from "@/lib/tajweed/rules";

const categoryRules = ["makharij-al-huruf", "noon-sakinah", "meem-sakinah", "madd-tabii", "waqf", "sifaat-al-huruf"]
  .map((id) => tajweedRules.find((rule) => rule.id === id))
  .filter((rule): rule is (typeof tajweedRules)[number] => Boolean(rule));
const coreRuleIds = ["izhar", "idgham", "iqlab", "ikhfa", "meem-sakinah", "qalqalah-letters", "madd-tabii", "lam-in-allah", "raa-heavy-and-light"];
const coreRules = coreRuleIds.map((id) => tajweedRules.find((rule) => rule.id === id)).filter((rule): rule is (typeof tajweedRules)[number] => Boolean(rule));
const learningStages = curriculumAreas.slice(0, 4);
const faqs = [
  ["Can I start if I am completely new to Tajweed?", "Yes. Begin with the Foundations path. It is designed to establish the vocabulary, reading habits, and listening approach needed for later rules."],
  ["Do I need to know Arabic?", "You do not need to speak Arabic to begin studying Tajweed, but you do need an appropriate foundation in reading Arabic script. A teacher can help assess where to start."],
  ["Is reading the explanations enough?", "No. Explanations support understanding, while correct pronunciation is developed through listening, repetition, and feedback from a qualified teacher or reciter."],
  ["How should I use the Quran examples?", "First identify the highlighted feature, then listen to a verified recitation, repeat carefully, and ask a teacher to check what you are hearing and producing."],
];

export default function Home() {
  return <><SiteHeader /><main>
    <section className="hero hero-home"><div className="container hero-grid"><div className="hero-copy"><Breadcrumbs /><p className="eyebrow">Learn Tajweed clearly, step by step</p><h1>Master Tajweed. Read the Quran with <span>confidence.</span></h1><p className="hero-lede">A structured English guide to Tajweed lessons, clear examples, listening guidance, practice exercises, and thoughtful learning resources.</p><div className="hero-actions"><Button href="/start-here">Start Learning</Button><a href="#rules" className="outline-link">Explore Tajweed Rules <ArrowRight size={16} /></a></div><div className="trust-row"><span><ShieldCheck size={17} /> Source-conscious content</span><span><Headphones size={17} /> Built for listening and practice</span></div></div><div className="hero-aside hero-dashboard"><div className="dashboard-top"><span className="eyebrow">Your first step</span><span className="badge">Foundations</span></div><div className="dashboard-arabic" lang="ar" dir="rtl">اقْرَأْ بِتَأَنٍّ</div><div className="dashboard-rule"><div className="rule-icon"><Volume2 size={18} /></div><div><strong>Listen for the difference</strong><small>Explanation · Demonstration · Practice</small></div></div><div className="dashboard-lines"><i /><i /><i /></div></div></div></section>
    <section className="search-section"><div className="container"><SearchPanel /></div></section>
    <section className="section intro-section"><div className="container intro-grid"><div><p className="eyebrow">Why learn Tajweed?</p><h2>Make careful reading a practice you can understand.</h2></div><div><p className="large-copy">Tajweed gives learners a way to study the details of Quranic recitation with greater awareness. This guide breaks those details into manageable lessons, then connects each idea to listening and practice.</p><p className="muted">The website explains concepts theoretically; pronunciation is best developed by hearing a qualified reciter and receiving feedback from a qualified teacher.</p></div></div></section>
    <section className="section tinted" id="learn"><div className="container"><div className="section-heading"><div><p className="eyebrow">Start here</p><h2>Follow the learning order</h2></div><a className="text-link" href="/tajweed">Open the full directory <ArrowRight size={14} /></a></div><div className="path-grid">{learningStages.map((stage, index) => <div key={stage.id} className="path-stage"><div className={index === 0 ? "path-step active" : "path-step"}><span className="level-index">0{index + 1}</span><div className="path-icon">{index === 0 ? <Target size={19} /> : index === 1 ? <Layers3 size={19} /> : index === 2 ? <CirclePlay size={19} /> : <Sparkles size={19} />}</div><h3>{stage.title}</h3><p>{stage.summary}</p><a className="text-link" href={`/tajweed/${stage.rules.map((id) => tajweedRules.find((rule) => rule.id === id)).find(Boolean)?.slug ?? "what-is-tajweed"}`}>Begin stage <ArrowRight size={14} /></a></div>{index < learningStages.length - 1 && <span className="path-connector" aria-hidden="true">→</span>}</div>)}</div></div></section>
    <section className="section" id="categories"><div className="container"><div className="section-heading"><div><p className="eyebrow">Major rule categories</p><h2>See how Tajweed is organised</h2></div><a className="text-link" href="/tajweed">Browse the directory <ArrowRight size={14} /></a></div><div className="category-grid">{categoryRules.map((rule) => <a className="category-card" href={`/tajweed/${rule.slug}`} key={rule.id}><span className="category-arrow"><ArrowRight size={16} /></span><p className="arabic-sm" lang="ar" dir="rtl">{rule.arabicName ?? rule.name}</p><h3>{rule.name}</h3><p className="muted">{rule.category}</p></a>)}</div></div></section>
    <section className="section tinted" id="rules"><div className="container"><div className="section-heading"><div><p className="eyebrow">Core Tajweed rules</p><h2>The rules learners meet most often</h2></div><a className="text-link" href="/tajweed">See all Tajweed rules <ArrowRight size={14} /></a></div><div className="rule-grid">{coreRules.map((rule) => <a className="rule-card card" href={`/tajweed/${rule.slug}`} key={rule.id}><div className="card-top"><span className="badge">{rule.level}</span><ArrowRight className="card-arrow" size={16} /></div><p className="arabic-sm" lang="ar" dir="rtl">{rule.arabicName}</p><h3>{rule.name}</h3><p className="muted">{rule.shortDefinition}</p><span className="text-link">Read the full lesson <ArrowRight size={14} /></span></a>)}</div></div></section>
    <section className="section how-section"><div className="container"><div className="center-heading"><p className="eyebrow">How it works</p><h2>Turn information into a listening habit.</h2></div><div className="how-grid">{[["01", "Learn", "Read the short explanation and learn the key term."], ["02", "Understand", "Connect the rule to what you already know."], ["03", "Observe examples", "Look at a verified, clearly marked example."], ["04", "Practise", "Listen, repeat, and work through a focused exercise."], ["05", "Review", "Return later and check what your ear now notices."]].map(([number, title, text]) => <div className="how-step" key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
    <section className="section beginner-section"><div className="container beginner-grid"><div className="beginner-art" aria-hidden="true"><BookOpen size={42} /><span>01</span></div><div><p className="eyebrow">Completely new?</p><h2>Start with the Foundations path.</h2><p className="large-copy">You do not need to know every term before you begin. Start with orientation, reading prerequisites, and the habits that make later lessons easier to follow.</p><div className="check-list"><span><CheckCircle2 size={17} /> Understand what each lesson is for</span><span><CheckCircle2 size={17} /> Learn how to use examples actively</span><span><CheckCircle2 size={17} /> Know when to ask a teacher for feedback</span></div><Button href="/learn/foundations" variant="secondary">Begin Foundations</Button></div></div></section>
    <section className="section soft" id="practice"><div className="container practice-grid"><div><p className="eyebrow">Practice, not pressure</p><h2>Use short exercises to make progress visible.</h2><p className="large-copy">Quizzes help you check recognition and understanding. Practice activities give you a reason to listen, repeat, and return to a rule over time.</p><a className="text-link" href="/practice">Explore practice resources <ArrowRight size={14} /></a></div><div className="stacked-cards"><QuranExample /><QuizCard /></div></div></section>
    <section className="section" id="articles"><div className="container"><div className="section-heading"><div><p className="eyebrow">Articles and guides</p><h2>Useful reading for the questions between lessons</h2></div><a className="text-link" href="/articles">View all articles <ArrowRight size={14} /></a></div><div className="article-grid"><article className="article-card featured-article"><span className="badge">Study guide</span><h3>How to Start Learning Tajweed</h3><p className="muted">A practical starting plan for complete beginners, including prerequisites, lesson rhythm, and when to seek teacher feedback.</p><a className="text-link" href="/articles/how-to-start-learning-tajweed">Read guide <ArrowRight size={14} /></a></article><article className="article-card"><span className="badge">Beginner</span><h3>Common Tajweed Mistakes Beginners Make</h3><p className="muted">A practical checklist of study mistakes that make Tajweed harder to learn, and how to replace them with better habits.</p><a className="text-link" href="/articles/common-tajweed-mistakes-beginners-make">Read guide <ArrowRight size={14} /></a></article><article className="article-card"><span className="badge">Practice</span><h3>How to Practice Tajweed Effectively</h3><p className="muted">A repeatable practice routine that balances explanation, listening, controlled repetition, and review.</p><a className="text-link" href="/articles/how-to-practice-tajweed-effectively">Read guide <ArrowRight size={14} /></a></article></div></div></section>
    <section className="section faq-section"><div className="container faq-grid"><div><p className="eyebrow">Frequently asked questions</p><h2>A clearer beginning starts with good questions.</h2><p className="muted">If your question is about your individual pronunciation, bring it to a qualified teacher or reciter.</p></div><div className="faq-list">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<ChevronDown size={18} /></summary><p>{answer}</p></details>)}</div></div></section>
    <section className="final-cta"><div className="container final-cta-inner"><div><p className="eyebrow">Your next step can be simple</p><h2>Start Learning Tajweed</h2><p>Begin with one lesson, one sound, and one focused practice.</p></div><Button href="/start-here">Start Learning</Button></div></section>
  </main><Footer /></>;
}
