import { ArrowRight, ChevronRight, Search } from "lucide-react";

import { searchPaletteIndex } from "@/lib/search";
import { SearchPalette } from "@/components/search-palette";
export { QuranExample } from "@/components/quran-example";
export { QuizCard } from "@/components/quiz-card";
export { SearchPalette } from "@/components/search-palette";
export { SiteHeader } from "@/components/site-header";
export { ThemeToggle } from "@/components/theme-toggle";

export function Button({ children, variant = "primary", href = "/learn" }: { children: React.ReactNode; variant?: "primary" | "secondary" | "quiet"; href?: string }) { const content = <>{children}{variant === "primary" && <ArrowRight size={16} />}</>; return href ? <a className={`button ${variant}`} href={href}>{content}</a> : <button className={`button ${variant}`} type="button">{content}</button>; }
export function Breadcrumbs() { return <div className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><ChevronRight size={14} /><span>Learn Tajweed</span></div>; }
export function Alert({ children, tone = "info" }: { children: React.ReactNode; tone?: "info" | "notice" }) { return <aside className={`alert ${tone}`} role="note"><span className="alert-mark">{tone === "notice" ? "!" : "i"}</span><span>{children}</span></aside>; }
export function InfoTable({ rows }: { rows: Array<[string, string]> }) { return <div className="table-wrap"><table><tbody>{rows.map(([label, value]) => <tr key={label}><th scope="row">{label}</th><td>{value}</td></tr>)}</tbody></table></div>; }
export function SearchPanel() { return <div className="search-panel-wrap"><form className="search-panel" action="/search" method="get"><Search size={20} /><input name="q" aria-label="Search the guide" list="search-suggestions" placeholder="Search rules, Arabic terms, or topics…" /><datalist id="search-suggestions"><option value="ikhfa" /><option value="noon sakinah" /><option value="madd" /><option value="qalqalah" /><option value="heavy letters" /><option value="makharij" /></datalist><kbd>⌘ K</kbd></form><SearchPalette index={searchPaletteIndex} /></div>; }
export function Footer() { return <footer className="site-footer"><div className="container footer-grid"><div><a href="/" className="brand footer-brand" aria-label="Tajweed101 home"><span className="brand-mark"><img src="/logo.png" alt="" /></span><span className="brand-name"><span>Tajweed101</span><small>Learn with clarity</small></span></a><p className="footer-copy">Clear explanations for a practice that is heard, guided, and lived.</p></div><div><h4>Explore</h4><a href="/learn">Learning path</a><a href="/tajweed">Rules library</a><a href="/practice">Practice</a><a href="/articles">Articles</a></div><div><h4>Trust & navigation</h4><a href="/editorial-policy">Editorial policy</a><a href="/about">About the guide</a><a href="/sitemap.xml">Sitemap</a></div></div><div className="container teacher-notice"><strong>A note for every learner</strong><span>Tajweed is best learned through listening, repetition, and practice with a qualified teacher or reciter. This guide supports that learning; it does not replace it.</span></div><div className="container footer-bottom"><span>© 2026 Complete Tajweed Guide</span><span>Built for careful learning.</span></div></footer>; }
