import { ArrowRight, BookOpen, ChevronRight, Search } from "lucide-react";
export { QuranExample } from "@/components/quran-example";
export { QuizCard } from "@/components/quiz-card";
export { SiteHeader } from "@/components/site-header";
export { ThemeToggle } from "@/components/theme-toggle";

export function Button({ children, variant = "primary", href }: { children: React.ReactNode; variant?: "primary" | "secondary" | "quiet"; href?: string }) { const content = <>{children}{variant === "primary" && <ArrowRight size={16} />}</>; return href ? <a className={`button ${variant}`} href={href}>{content}</a> : <button className={`button ${variant}`} type="button">{content}</button>; }
export function Breadcrumbs() { return <div className="breadcrumbs" aria-label="Breadcrumb"><a href="/">Home</a><ChevronRight size={14} /><span>Learn Tajweed</span></div>; }
export function RuleCard({ title, description, level, arabic }: { title: string; description: string; level: string; arabic: string }) { const slugs: Record<string, string> = { Makharij: "makharij", "Noon Sakinah and Tanween": "noon-sakinah", "Meem Sakinah": "meem-sakinah", Madd: "madd-tabii" }; return <article className="card rule-card"><div className="card-top"><span className="badge">{level}</span><span className="card-arrow"><ArrowRight size={17} /></span></div><p className="arabic-sm" lang="ar" dir="rtl">{arabic}</p><h3>{title}</h3><p className="muted">{description}</p><a className="text-link" href={`/tajweed/${slugs[title] ?? title.toLowerCase().replaceAll(" ", "-")}`}>Explore rule <ArrowRight size={14} /></a></article>; }
export function ProgressCard() { return <section className="card progress-card" id="practice"><div className="progress-title"><div><span className="eyebrow">Your learning path</span><h3>Build a steady practice</h3></div><span className="progress-number">02 <small>/ 12</small></span></div><div className="progress-track"><span style={{ width: "18%" }} /></div><p className="muted">Start with the foundations, then return to practice as your ear develops.</p><a className="button secondary" href="/learn">View learning path <ArrowRight size={16} /></a></section>; }
export function SearchPanel() { return <form className="search-panel" action="/search" method="get"><Search size={20} /><input name="q" aria-label="Search the guide" list="search-suggestions" placeholder="Search rules, Arabic terms, or topics…" /><datalist id="search-suggestions"><option value="ikhfa" /><option value="noon sakinah" /><option value="madd" /><option value="qalqalah" /><option value="heavy letters" /><option value="makharij" /></datalist><kbd>⌘ K</kbd></form>; }
export function Alert({ children, tone = "info" }: { children: React.ReactNode; tone?: "info" | "notice" }) { return <aside className={`alert ${tone}`} role="note"><span className="alert-mark">{tone === "notice" ? "!" : "i"}</span><span>{children}</span></aside>; }
export function RuleHighlight({ children, label = "Rule focus" }: { children: React.ReactNode; label?: string }) { return <span className="rule-highlight"><span className="sr-only">{label}: </span>{children}</span>; }
export function InfoTable({ rows }: { rows: Array<[string, string]> }) { return <div className="table-wrap"><table><tbody>{rows.map(([label, value]) => <tr key={label}><th scope="row">{label}</th><td>{value}</td></tr>)}</tbody></table></div>; }
export function Footer() { return <footer className="site-footer"><div className="container footer-grid"><div><a href="/" className="brand footer-brand"><span className="brand-mark"><BookOpen size={18} /></span><span>Complete <em>Tajweed</em> Guide</span></a><p className="footer-copy">Clear explanations for a practice that is heard, guided, and lived.</p></div><div><h4>Explore</h4><a href="/learn">Learning path</a><a href="/tajweed">Rules library</a><a href="/practice">Practice</a><a href="/articles">Articles</a></div><div><h4>Trust & navigation</h4><a href="/editorial-policy">Editorial policy</a><a href="/sources">Sources</a><a href="/about">About the guide</a><a href="/sitemap.xml">Sitemap</a></div></div><div className="container teacher-notice"><strong>A note for every learner</strong><span>Tajweed is best learned through listening, repetition, and practice with a qualified teacher or reciter. This guide supports that learning; it does not replace it.</span></div><div className="container footer-bottom"><span>© 2026 Complete Tajweed Guide</span><span>Built for careful learning.</span></div></footer>; }
