import type { LearningLevel, TajweedLevel, TajweedTopic } from "./types";

export const READING_TRADITION = "Hafs ʿan ʿĀṣim — initial scope";

export const tajweedLevels: TajweedLevel[] = [
  { id: "foundations", level: 1, title: "Foundations", slug: "foundations", purpose: "Build the reading, articulation, and listening foundations needed for every later topic.", topicIds: ["arabic-letters", "basic-arabic-pronunciation", "makharij", "sifaat", "heavy-and-light-letters"] },
  { id: "essential-rules", level: 2, title: "Essential Tajweed Rules", slug: "essential-rules", purpose: "Recognise the recurring rules that arise around Noon, Tanween, Meem, Qalqalah, Laam, and Raa.", topicIds: ["noon-sakinah", "tanween", "izhar", "idgham", "iqlab", "ikhfa", "meem-sakinah", "ikhfa-shafawi", "idgham-shafawi", "izhar-shafawi", "qalqalah", "lam-rules", "raa-rules"] },
  { id: "madd", level: 3, title: "Madd and Lengthening", slug: "madd-and-lengthening", purpose: "Organise the main Madd families from natural lengthening to context-dependent and stopping-related forms.", topicIds: ["madd-tabii", "madd-badal", "madd-lin", "madd-arid-lis-sukun", "madd-wajib-muttasil", "madd-jaiz-munfasil", "madd-lazim-kalimi", "madd-lazim-harfi"] },
  { id: "stopping-starting", level: 4, title: "Stopping and Starting", slug: "stopping-and-starting", purpose: "Learn to recognise stopping signs and approach pauses and new beginnings with context and guidance.", topicIds: ["waqf", "ibtida", "stop-signs", "types-of-waqf", "how-to-resume"] },
  { id: "advanced-topics", level: 5, title: "Advanced Topics", slug: "advanced-topics", purpose: "Study interactions and tradition-specific details only after the core rule families are stable.", topicIds: ["noon-and-meem-mushaddad", "idgham-between-letters", "tafkhim-and-tarqiq", "hamzatul-wasl", "cutting-and-joining", "recitation-modes"] },
];

const topic = (value: TajweedTopic): TajweedTopic => value;

export const tajweedTopics: TajweedTopic[] = [
  topic({ id: "arabic-letters", title: "Arabic Letters", arabicName: "حُرُوفُ الْهِجَاءِ", transliteration: "Ḥurūf al-hijāʾ", level: 1, category: "Foundations", summary: "Recognise the Arabic letters and their written forms before studying their detailed articulation.", prerequisites: [], relatedRules: ["basic-arabic-pronunciation", "makharij"], suggestedOrder: 1, estimatedDifficulty: "introductory", slug: "arabic-letters", seoTopic: "Arabic letters for Quran reading", practiceType: ["recognition"], tags: ["letters", "alphabet", "reading"], readingTraditions: ["All reading traditions"], reviewStatus: "needs-qualified-review", sourceIds: ["mcec-quran-curriculum"] }),
  topic({ id: "basic-arabic-pronunciation", title: "Basic Arabic Pronunciation", arabicName: "الحَرَكَاتُ وَالسُّكُونُ", transliteration: "al-ḥarakāt wa-s-sukūn", level: 1, category: "Foundations", summary: "Practise the basic vowel signs and reading symbols used in Quranic Arabic before applying rule families.", prerequisites: ["arabic-letters"], relatedRules: ["makharij", "madd-tabii"], suggestedOrder: 2, estimatedDifficulty: "introductory", slug: "basic-arabic-pronunciation", seoTopic: "basic Arabic pronunciation for Quran reading", practiceType: ["recognition", "articulation"], tags: ["harakat", "sukoon", "vowels"], readingTraditions: ["All reading traditions"], reviewStatus: "needs-qualified-review", sourceIds: ["mcec-quran-curriculum"] }),
  topic({ id: "makharij", title: "Makharij", arabicName: "مَخَارِجُ الْحُرُوفِ", transliteration: "Mak hārij al-ḥurūf", level: 1, category: "Foundations", summary: "Study the articulation points of the Arabic letters with teacher-led listening and correction.", prerequisites: ["arabic-letters", "basic-arabic-pronunciation"], relatedRules: ["sifaat", "heavy-and-light-letters", "qalqalah"], suggestedOrder: 3, estimatedDifficulty: "developing", slug: "makharij", seoTopic: "Makharij articulation points", practiceType: ["articulation", "listening", "guided-repetition"], tags: ["articulation", "pronunciation", "makhraj"], readingTraditions: ["All reading traditions"], reviewStatus: "needs-qualified-review", sourceIds: ["recite-with-love-curriculum", "mcec-quran-curriculum"] }),
  topic({ id: "sifaat", title: "Sifaat", arabicName: "صِفَاتُ الْحُرُوفِ", transliteration: "Ṣifāt al-ḥurūf", level: 1, category: "Foundations", summary: "Learn the qualities used to describe and distinguish Arabic letter sounds.", prerequisites: ["makharij"], relatedRules: ["heavy-and-light-letters", "tafkhim-and-tarqiq", "qalqalah"], suggestedOrder: 4, estimatedDifficulty: "developing", slug: "sifaat", seoTopic: "Sifaat letter qualities in Tajweed", practiceType: ["listening", "articulation", "guided-repetition"], tags: ["letter qualities", "sifaat"], readingTraditions: ["All reading traditions"], reviewStatus: "needs-qualified-review", sourceIds: ["recite-with-love-curriculum", "mcec-quran-curriculum"] }),
  topic({ id: "heavy-and-light-letters", title: "Heavy and Light Letters", arabicName: "التَّفْخِيمُ وَالتَّرْقِيقُ", transliteration: "Tafkhīm wa tarqīq", level: 1, category: "Foundations", summary: "Build an ear for the contrast between heavier and lighter letter qualities before studying context-specific cases.", prerequisites: ["makharij", "sifaat"], relatedRules: ["lam-rules", "raa-rules", "tafkhim-and-tarqiq"], suggestedOrder: 5, estimatedDifficulty: "developing", slug: "heavy-and-light-letters", seoTopic: "heavy and light letters in Tajweed", practiceType: ["listening", "guided-repetition"], tags: ["tafkhim", "tarqiq", "heavy", "light"], readingTraditions: ["All reading traditions"], reviewStatus: "needs-qualified-review", sourceIds: ["recite-with-love-curriculum"] }),

  topic({ id: "noon-sakinah", title: "Noon Sakinah", arabicName: "النُّونُ السَّاكِنَةُ", transliteration: "Nūn sākinah", level: 2, category: "Noon and Tanween", summary: "Identify Noon with sukoon as the entry point to its connected rule family.", prerequisites: ["basic-arabic-pronunciation", "makharij"], relatedRules: ["tanween", "izhar", "idgham", "iqlab", "ikhfa"], suggestedOrder: 6, estimatedDifficulty: "developing", slug: "noon-sakinah", seoTopic: "Noon Sakinah Tajweed rules", practiceType: ["recognition", "listening"], tags: ["noon", "sakinah", "nun"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["tajweed-rules-reference", "recite-with-love-curriculum"] }),
  topic({ id: "tanween", title: "Tanween", arabicName: "التَّنْوِينُ", transliteration: "Tanwīn", level: 2, category: "Noon and Tanween", summary: "Recognise tanween and connect it to the same core rule family as Noon Sakinah.", prerequisites: ["basic-arabic-pronunciation", "noon-sakinah"], relatedRules: ["izhar", "idgham", "iqlab", "ikhfa"], suggestedOrder: 7, estimatedDifficulty: "developing", slug: "tanween", seoTopic: "Tanween Tajweed rules", practiceType: ["recognition", "listening"], tags: ["tanween", "nunation"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["tajweed-rules-reference", "recite-with-love-curriculum"] }),
  topic({ id: "izhar", title: "Izhar", arabicName: "الإِظْهَارُ", transliteration: "Iẓhār", level: 2, category: "Noon and Tanween", summary: "Study the clear-reading case within the Noon Sakinah and Tanween family.", prerequisites: ["noon-sakinah", "tanween"], relatedRules: ["idgham", "iqlab", "ikhfa", "izhar-shafawi"], suggestedOrder: 8, estimatedDifficulty: "developing", slug: "izhar", seoTopic: "Izhar Tajweed rule", practiceType: ["recognition", "listening", "guided-repetition"], tags: ["izhar", "clear reading"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["tajweed-rules-reference"] }),
  topic({ id: "idgham", title: "Idgham", arabicName: "الإِدْغَامُ", transliteration: "Idghām", level: 2, category: "Noon and Tanween", summary: "Study the merging case within the Noon Sakinah and Tanween family, including its qualified subcases.", prerequisites: ["noon-sakinah", "tanween", "makharij"], relatedRules: ["izhar", "iqlab", "ikhfa", "idgham-shafawi", "idgham-between-letters"], suggestedOrder: 9, estimatedDifficulty: "developing", slug: "idgham", seoTopic: "Idgham Tajweed rule", practiceType: ["recognition", "listening", "guided-repetition"], tags: ["idgham", "merging"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["tajweed-rules-reference", "recite-with-love-curriculum"] }),
  topic({ id: "iqlab", title: "Iqlab", arabicName: "الإِقْلَابُ", transliteration: "Iqlāb", level: 2, category: "Noon and Tanween", summary: "Study the specific Noon Sakinah and Tanween case traditionally treated as Iqlab.", prerequisites: ["noon-sakinah", "tanween", "makharij"], relatedRules: ["izhar", "idgham", "ikhfa"], suggestedOrder: 10, estimatedDifficulty: "developing", slug: "iqlab", seoTopic: "Iqlab Tajweed rule", practiceType: ["recognition", "listening", "guided-repetition"], tags: ["iqlab", "noon", "tanween"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["tajweed-rules-reference"] }),
  topic({ id: "ikhfa", title: "Ikhfa", arabicName: "الإِخْفَاءُ", transliteration: "Ikhfāʾ", level: 2, category: "Noon and Tanween", summary: "Study the partially concealed case within the Noon Sakinah and Tanween family through listening and guided repetition.", prerequisites: ["noon-sakinah", "tanween", "sifaat"], relatedRules: ["izhar", "idgham", "iqlab", "ikhfa-shafawi"], suggestedOrder: 11, estimatedDifficulty: "consolidating", slug: "ikhfa", seoTopic: "Ikhfa Tajweed rule", practiceType: ["recognition", "listening", "guided-repetition"], tags: ["ikhfa", "concealment"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["tajweed-rules-reference"] }),
  topic({ id: "meem-sakinah", title: "Meem Sakinah", arabicName: "المِيمُ السَّاكِنَةُ", transliteration: "Mīm sākinah", level: 2, category: "Meem Sakinah", summary: "Identify Meem with sukoon as the entry point to its three commonly taught cases.", prerequisites: ["basic-arabic-pronunciation", "makharij"], relatedRules: ["ikhfa-shafawi", "idgham-shafawi", "izhar-shafawi"], suggestedOrder: 12, estimatedDifficulty: "developing", slug: "meem-sakinah", seoTopic: "Meem Sakinah Tajweed rules", practiceType: ["recognition", "listening"], tags: ["meem", "sakinah"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["tajweed-rules-reference", "recite-with-love-curriculum"] }),
  topic({ id: "ikhfa-shafawi", title: "Ikhfa Shafawi", arabicName: "الإِخْفَاءُ الشَّفَوِيُّ", transliteration: "Ikhfāʾ shafawī", level: 2, category: "Meem Sakinah", summary: "Study the lip-related concealment case of Meem Sakinah with qualified listening guidance.", prerequisites: ["meem-sakinah", "makharij"], relatedRules: ["ikhfa", "idgham-shafawi", "izhar-shafawi"], suggestedOrder: 13, estimatedDifficulty: "consolidating", slug: "ikhfa-shafawi", seoTopic: "Ikhfa Shafawi Tajweed rule", practiceType: ["listening", "guided-repetition"], tags: ["meem", "shafawi", "ikhfa"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["tajweed-rules-reference"] }),
  topic({ id: "idgham-shafawi", title: "Idgham Shafawi", arabicName: "الإِدْغَامُ الشَّفَوِيُّ", transliteration: "Idghām shafawī", level: 2, category: "Meem Sakinah", summary: "Study the lip-related merging case of Meem Sakinah.", prerequisites: ["meem-sakinah", "makharij"], relatedRules: ["idgham", "ikhfa-shafawi", "izhar-shafawi"], suggestedOrder: 14, estimatedDifficulty: "consolidating", slug: "idgham-shafawi", seoTopic: "Idgham Shafawi Tajweed rule", practiceType: ["listening", "guided-repetition"], tags: ["meem", "shafawi", "idgham"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["tajweed-rules-reference"] }),
  topic({ id: "izhar-shafawi", title: "Izhar Shafawi", arabicName: "الإِظْهَارُ الشَّفَوِيُّ", transliteration: "Iẓhār shafawī", level: 2, category: "Meem Sakinah", summary: "Study the clear-reading case of Meem Sakinah when the other two cases do not apply.", prerequisites: ["meem-sakinah", "makharij"], relatedRules: ["izhar", "ikhfa-shafawi", "idgham-shafawi"], suggestedOrder: 15, estimatedDifficulty: "consolidating", slug: "izhar-shafawi", seoTopic: "Izhar Shafawi Tajweed rule", practiceType: ["recognition", "listening", "guided-repetition"], tags: ["meem", "shafawi", "izhar"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["tajweed-rules-reference"] }),
  topic({ id: "qalqalah", title: "Qalqalah", arabicName: "القَلْقَلَةُ", transliteration: "Qalqalah", level: 2, category: "Letter qualities", summary: "Recognise and practise the characteristic commonly taught as Qalqalah, with attention to position and degree.", prerequisites: ["makharij", "sifaat"], relatedRules: ["sifaat", "waqf", "heavy-and-light-letters"], suggestedOrder: 16, estimatedDifficulty: "consolidating", slug: "qalqalah", seoTopic: "Qalqalah Tajweed rule", practiceType: ["recognition", "listening", "guided-repetition"], tags: ["qalqalah", "echo"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["recite-with-love-curriculum", "tajweed-rules-reference"] }),
  topic({ id: "lam-rules", title: "Lam Rules", arabicName: "أَحْكَامُ اللَّامِ", transliteration: "Aḥkām al-lām", level: 2, category: "Lam and Raa", summary: "Study the main Lam cases included in the selected curriculum, with examples verified for the reading tradition.", prerequisites: ["makharij", "heavy-and-light-letters"], relatedRules: ["raa-rules", "tafkhim-and-tarqiq", "hamzatul-wasl"], suggestedOrder: 17, estimatedDifficulty: "consolidating", slug: "lam-rules", seoTopic: "Lam rules in Tajweed", practiceType: ["recognition", "listening"], tags: ["lam", "tafkhim", "tarqiq"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm scope"], reviewStatus: "tradition-specific-review", sourceIds: ["recite-with-love-curriculum"] }),
  topic({ id: "raa-rules", title: "Raa Rules", arabicName: "أَحْكَامُ الرَّاءِ", transliteration: "Aḥkām al-rāʾ", level: 2, category: "Lam and Raa", summary: "Study when Raa is treated as heavy or light within the selected reading tradition.", prerequisites: ["makharij", "sifaat", "heavy-and-light-letters"], relatedRules: ["lam-rules", "tafkhim-and-tarqiq", "waqf"], suggestedOrder: 18, estimatedDifficulty: "consolidating", slug: "raa-rules", seoTopic: "Raa rules in Tajweed", practiceType: ["recognition", "listening", "guided-repetition"], tags: ["raa", "tafkhim", "tarqiq"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm scope"], reviewStatus: "tradition-specific-review", sourceIds: ["recite-with-love-curriculum"] }),

  topic({ id: "madd-tabii", title: "Madd Tabii", arabicName: "المَدُّ الطَّبِيعِيُّ", transliteration: "Madd ṭabīʿī", level: 3, category: "Madd and lengthening", summary: "Begin Madd with the natural lengthening category before studying causes that change it.", prerequisites: ["basic-arabic-pronunciation", "makharij"], relatedRules: ["madd-badal", "madd-lin", "madd-wajib-muttasil", "madd-jaiz-munfasil"], suggestedOrder: 19, estimatedDifficulty: "developing", slug: "madd-tabii", seoTopic: "Madd Tabii natural elongation", practiceType: ["recognition", "listening", "guided-repetition"], tags: ["madd", "lengthening", "natural madd"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["tajweed-rules-reference", "recite-with-love-curriculum"] }),
  topic({ id: "madd-badal", title: "Madd Badal", arabicName: "مَدُّ الْبَدَلِ", transliteration: "Madd badal", level: 3, category: "Madd and lengthening", summary: "Study the Madd category traditionally taught as Badal after the natural Madd foundation.", prerequisites: ["madd-tabii"], relatedRules: ["madd-wajib-muttasil", "madd-jaiz-munfasil"], suggestedOrder: 20, estimatedDifficulty: "consolidating", slug: "madd-badal", seoTopic: "Madd Badal Tajweed rule", practiceType: ["recognition", "listening"], tags: ["madd", "badal"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm scope"], reviewStatus: "tradition-specific-review", sourceIds: ["tajweed-rules-reference", "recite-with-love-curriculum"] }),
  topic({ id: "madd-lin", title: "Madd Lin", arabicName: "مَدُّ اللِّينِ", transliteration: "Madd līn", level: 3, category: "Madd and lengthening", summary: "Study the soft-letter Madd category and its relationship to stopping.", prerequisites: ["madd-tabii", "waqf"], relatedRules: ["madd-arid-lis-sukun", "waqf"], suggestedOrder: 21, estimatedDifficulty: "consolidating", slug: "madd-lin", seoTopic: "Madd Lin Tajweed rule", practiceType: ["recognition", "listening", "stop-start"], tags: ["madd", "leen", "stopping"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm scope"], reviewStatus: "tradition-specific-review", sourceIds: ["tajweed-rules-reference"] }),
  topic({ id: "madd-arid-lis-sukun", title: "Madd Arid li-s-Sukun", arabicName: "مَدُّ عَارِضٍ لِلسُّكُونِ", transliteration: "Madd ʿāriḍ li-s-sukūn", level: 3, category: "Madd and lengthening", summary: "Study the Madd case that is connected to a temporary sukoon arising at a stop.", prerequisites: ["madd-tabii", "waqf"], relatedRules: ["madd-lin", "waqf", "stop-signs"], suggestedOrder: 22, estimatedDifficulty: "consolidating", slug: "madd-arid-lis-sukun", seoTopic: "Madd Arid li-s-Sukun Tajweed", practiceType: ["recognition", "listening", "stop-start"], tags: ["madd", "sukoon", "stopping"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm scope"], reviewStatus: "tradition-specific-review", sourceIds: ["tajweed-rules-reference", "recite-with-love-curriculum"] }),
  topic({ id: "madd-wajib-muttasil", title: "Madd Wajib Muttasil", arabicName: "المَدُّ الْوَاجِبُ الْمُتَّصِلُ", transliteration: "Madd wājib muttaṣil", level: 3, category: "Madd and lengthening", summary: "Study the connected Madd category traditionally taught when the relevant cause occurs within one word.", prerequisites: ["madd-tabii"], relatedRules: ["madd-jaiz-munfasil", "madd-badal"], suggestedOrder: 23, estimatedDifficulty: "consolidating", slug: "madd-wajib-muttasil", seoTopic: "Madd Wajib Muttasil Tajweed", practiceType: ["recognition", "listening"], tags: ["madd", "hamzah", "connected"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm scope"], reviewStatus: "tradition-specific-review", sourceIds: ["tajweed-rules-reference", "recite-with-love-curriculum"] }),
  topic({ id: "madd-jaiz-munfasil", title: "Madd Jaiz Munfasil", arabicName: "المَدُّ الْجَائِزُ الْمُنْفَصِلُ", transliteration: "Madd jāʾiz munfaṣil", level: 3, category: "Madd and lengthening", summary: "Study the separated Madd category traditionally taught when the relevant letters span two words.", prerequisites: ["madd-tabii"], relatedRules: ["madd-wajib-muttasil", "madd-arid-lis-sukun"], suggestedOrder: 24, estimatedDifficulty: "consolidating", slug: "madd-jaiz-munfasil", seoTopic: "Madd Jaiz Munfasil Tajweed", practiceType: ["recognition", "listening"], tags: ["madd", "hamzah", "separated"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm scope"], reviewStatus: "tradition-specific-review", sourceIds: ["tajweed-rules-reference", "recite-with-love-curriculum"] }),
  topic({ id: "madd-lazim-kalimi", title: "Madd Lazim Kalimi", arabicName: "المَدُّ اللَّازِمُ الْكَلِمِيُّ", transliteration: "Madd lāzim kalimī", level: 3, category: "Madd and lengthening", summary: "Study the word-based Lazim category after the core Madd families are secure.", prerequisites: ["madd-tabii", "madd-wajib-muttasil"], relatedRules: ["madd-lazim-harfi", "madd-arid-lis-sukun"], suggestedOrder: 25, estimatedDifficulty: "advanced", slug: "madd-lazim-kalimi", seoTopic: "Madd Lazim Kalimi Tajweed", practiceType: ["recognition", "listening"], tags: ["madd", "lazim", "kalimi"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm scope"], reviewStatus: "tradition-specific-review", sourceIds: ["tajweed-rules-reference", "recite-with-love-curriculum"] }),
  topic({ id: "madd-lazim-harfi", title: "Madd Lazim Harfi", arabicName: "المَدُّ اللَّازِمُ الْحَرْفِيُّ", transliteration: "Madd lāzim ḥarfī", level: 3, category: "Madd and lengthening", summary: "Study the letter-based Lazim category in the context where it is relevant to the selected reading tradition.", prerequisites: ["madd-tabii", "madd-lazim-kalimi"], relatedRules: ["madd-lazim-kalimi", "recitation-modes"], suggestedOrder: 26, estimatedDifficulty: "advanced", slug: "madd-lazim-harfi", seoTopic: "Madd Lazim Harfi Tajweed", practiceType: ["recognition", "listening"], tags: ["madd", "lazim", "harfi"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm scope"], reviewStatus: "tradition-specific-review", sourceIds: ["tajweed-rules-reference", "recite-with-love-curriculum"] }),

  topic({ id: "waqf", title: "Waqf", arabicName: "الْوَقْفُ", transliteration: "Waqf", level: 4, category: "Stopping and starting", summary: "Understand the purpose of stopping and how a stop affects the sound at the end of a reading unit.", prerequisites: ["basic-arabic-pronunciation", "madd-tabii"], relatedRules: ["ibtida", "stop-signs", "types-of-waqf", "madd-arid-lis-sukun"], suggestedOrder: 27, estimatedDifficulty: "consolidating", slug: "waqf", seoTopic: "Waqf stopping in Tajweed", practiceType: ["recognition", "stop-start", "listening"], tags: ["waqf", "stop", "pausing"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["recite-with-love-curriculum", "mcec-quran-curriculum"] }),
  topic({ id: "ibtida", title: "Ibtida", arabicName: "الِابْتِدَاءُ", transliteration: "Ibtidāʾ", level: 4, category: "Stopping and starting", summary: "Study how to resume or begin recitation thoughtfully after a stop, with attention to context.", prerequisites: ["waqf"], relatedRules: ["stop-signs", "types-of-waqf", "how-to-resume"], suggestedOrder: 28, estimatedDifficulty: "consolidating", slug: "ibtida", seoTopic: "Ibtida starting recitation in Tajweed", practiceType: ["stop-start", "application"], tags: ["ibtida", "starting", "resuming"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["recite-with-love-curriculum", "mcec-quran-curriculum"] }),
  topic({ id: "stop-signs", title: "Stopping Signs", arabicName: "عَلَامَاتُ الْوَقْفِ", transliteration: "ʿAlāmāt al-waqf", level: 4, category: "Stopping and starting", summary: "Learn to recognise the stopping symbols used by the selected Mushaf and confirm their interpretation with a teacher.", prerequisites: ["waqf"], relatedRules: ["ibtida", "types-of-waqf", "madd-arid-lis-sukun"], suggestedOrder: 29, estimatedDifficulty: "consolidating", slug: "stopping-signs", seoTopic: "Quran stopping signs Tajweed", practiceType: ["recognition", "stop-start"], tags: ["waqf signs", "mushaf symbols"], readingTraditions: ["Hafs ʿan ʿĀṣim — Mushaf-specific"], reviewStatus: "tradition-specific-review", sourceIds: ["mcec-quran-curriculum"] }),
  topic({ id: "types-of-waqf", title: "Types of Waqf", arabicName: "أَقْسَامُ الْوَقْفِ", transliteration: "Aqsām al-waqf", level: 4, category: "Stopping and starting", summary: "Organise the principal types of stopping used in the selected curriculum before applying them to passages.", prerequisites: ["waqf", "ibtida"], relatedRules: ["stop-signs", "how-to-resume"], suggestedOrder: 30, estimatedDifficulty: "advanced", slug: "types-of-waqf", seoTopic: "types of Waqf in Tajweed", practiceType: ["recognition", "application", "stop-start"], tags: ["waqf", "classification", "stopping"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm terminology"], reviewStatus: "tradition-specific-review", sourceIds: ["recite-with-love-curriculum"] }),
  topic({ id: "how-to-resume", title: "How to Resume After a Stop", arabicName: "الِابْتِدَاءُ بَعْدَ الْوَقْفِ", transliteration: "Ibtidāʾ baʿda al-waqf", level: 4, category: "Stopping and starting", summary: "Practise choosing a clear and context-aware place to resume after stopping.", prerequisites: ["waqf", "ibtida", "stop-signs"], relatedRules: ["types-of-waqf", "madd-arid-lis-sukun"], suggestedOrder: 31, estimatedDifficulty: "advanced", slug: "how-to-resume-after-a-stop", seoTopic: "how to resume Quran recitation after stopping", practiceType: ["stop-start", "application", "listening"], tags: ["resume", "ibtida", "waqf"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["recite-with-love-curriculum"] }),

  topic({ id: "noon-and-meem-mushaddad", title: "Noon and Meem Mushaddad", arabicName: "النُّونُ وَالْمِيمُ الْمُشَدَّدَتَانِ", transliteration: "Nūn wa mīm mushaddadān", level: 5, category: "Advanced interaction", summary: "Study the reinforced Noon and Meem cases after their articulation and connected rule families are stable.", prerequisites: ["noon-sakinah", "meem-sakinah", "sifaat"], relatedRules: ["ikhfa", "idgham", "idgham-shafawi"], suggestedOrder: 32, estimatedDifficulty: "advanced", slug: "noon-and-meem-mushaddad", seoTopic: "Noon and Meem Mushaddad Tajweed", practiceType: ["recognition", "listening", "guided-repetition"], tags: ["ghunnah", "noon", "meem", "shaddah"], readingTraditions: ["Hafs ʿan ʿĀṣim", "All reading traditions — verify details"], reviewStatus: "needs-qualified-review", sourceIds: ["recite-with-love-curriculum"] }),
  topic({ id: "idgham-between-letters", title: "Idgham Between Letters", arabicName: "إِدْغَامُ الْحُرُوفِ", transliteration: "Idghām bayna al-ḥurūf", level: 5, category: "Advanced interaction", summary: "Study additional letter-to-letter merging patterns only after the core Noon and Meem families are secure.", prerequisites: ["idgham", "makharij", "sifaat"], relatedRules: ["idgham-shafawi", "noon-and-meem-mushaddad"], suggestedOrder: 33, estimatedDifficulty: "advanced", slug: "idgham-between-letters", seoTopic: "Idgham between letters Tajweed", practiceType: ["recognition", "listening", "guided-repetition"], tags: ["idgham", "letter interaction"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm scope"], reviewStatus: "tradition-specific-review", sourceIds: ["recite-with-love-curriculum"] }),
  topic({ id: "tafkhim-and-tarqiq", title: "Tafkhim and Tarqiq in Context", arabicName: "التَّفْخِيمُ وَالتَّرْقِيقُ", transliteration: "Tafkhīm wa tarqīq", level: 5, category: "Advanced interaction", summary: "Apply heaviness and lightness with the context-sensitive cases that follow foundational study.", prerequisites: ["sifaat", "heavy-and-light-letters", "lam-rules", "raa-rules"], relatedRules: ["lam-rules", "raa-rules"], suggestedOrder: 34, estimatedDifficulty: "advanced", slug: "tafkhim-and-tarqiq", seoTopic: "Tafkhim and Tarqiq in Tajweed", practiceType: ["listening", "guided-repetition", "application"], tags: ["tafkhim", "tarqiq", "context"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm scope"], reviewStatus: "tradition-specific-review", sourceIds: ["recite-with-love-curriculum"] }),
  topic({ id: "hamzatul-wasl", title: "Hamzat al-Wasl", arabicName: "هَمْزَةُ الْوَصْلِ", transliteration: "Hamzat al-waṣl", level: 5, category: "Advanced interaction", summary: "Study the connecting Hamzah in the context of beginning and joining recitation.", prerequisites: ["ibtida", "basic-arabic-pronunciation"], relatedRules: ["waqf", "how-to-resume", "lam-rules"], suggestedOrder: 35, estimatedDifficulty: "advanced", slug: "hamzat-al-wasl", seoTopic: "Hamzat al-Wasl Tajweed", practiceType: ["recognition", "listening", "stop-start"], tags: ["hamzah", "wasl", "joining"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm scope"], reviewStatus: "tradition-specific-review", sourceIds: ["recite-with-love-curriculum"] }),
  topic({ id: "cutting-and-joining", title: "Cutting and Joining", arabicName: "الْقَطْعُ وَالْوَصْلُ", transliteration: "al-Qaṭʿ wa-l-waṣl", level: 5, category: "Advanced interaction", summary: "Explore advanced decisions about separating and joining written or recited units where the selected tradition requires it.", prerequisites: ["waqf", "ibtida", "hamzatul-wasl"], relatedRules: ["stop-signs", "how-to-resume", "recitation-modes"], suggestedOrder: 36, estimatedDifficulty: "advanced", slug: "cutting-and-joining", seoTopic: "cutting and joining in Quran recitation", practiceType: ["recognition", "stop-start", "application"], tags: ["wasl", "qat", "joining"], readingTraditions: ["Hafs ʿan ʿĀṣim — confirm scope"], reviewStatus: "tradition-specific-review", sourceIds: ["recite-with-love-curriculum"] }),
  topic({ id: "recitation-modes", title: "Recitation Modes", arabicName: "مَرَاتِبُ التِّلَاوَةِ", transliteration: "Marātib al-tilāwah", level: 5, category: "Advanced interaction", summary: "Study the selected curriculum's treatment of recitation pace and delivery only with qualified instruction.", prerequisites: ["madd-tabii", "waqf", "ibtida", "makharij"], relatedRules: ["madd-wajib-muttasil", "types-of-waqf"], suggestedOrder: 37, estimatedDifficulty: "advanced", slug: "recitation-modes", seoTopic: "recitation modes in Tajweed", practiceType: ["listening", "application"], tags: ["tarteel", "recitation", "pace"], readingTraditions: ["Hafs ʿan ʿĀṣim — curriculum-specific"], reviewStatus: "tradition-specific-review", sourceIds: ["mcec-quran-curriculum"], taxonomyNote: "This is a curriculum topic, not a universal rule page. Define the terms and scope with a qualified reviewer before publishing." }),
];

export function getTopicBySlug(slug: string) { return tajweedTopics.find((item) => item.slug === slug); }
export function getTopicsByLevel(level: LearningLevel) { return tajweedTopics.filter((item) => item.level === level).sort((a, b) => a.suggestedOrder - b.suggestedOrder); }
export function getTopicsByCategory(category: string) { return tajweedTopics.filter((item) => item.category === category).sort((a, b) => a.suggestedOrder - b.suggestedOrder); }
export function searchTopics(query: string) { const normalized = query.trim().toLowerCase(); if (!normalized) return tajweedTopics; return tajweedTopics.filter((item) => [item.title, item.arabicName, item.transliteration, item.category, item.seoTopic, ...item.tags].filter(Boolean).join(" ").toLowerCase().includes(normalized)); }
