import { ArrowRight } from "lucide-react";
import { Footer, SiteHeader } from "@/components/ui";
import { articles } from "@/lib/articles/content";

export const metadata = { title: "Articles and Learning Guides | Complete Tajweed Guide", description: "Useful Tajweed articles answering real learner questions about rules, pronunciation, Quran reading, and practice.", alternates: { canonical: "/articles" }, openGraph: { title: "Articles and Learning Guides | Complete Tajweed Guide", description: "Useful Tajweed articles answering real learner questions about rules, pronunciation, Quran reading, and practice.", url: "/articles", type: "website" }, twitter: { card: "summary", title: "Articles and Learning Guides | Complete Tajweed Guide", description: "Useful Tajweed articles answering real learner questions about rules, pronunciation, Quran reading, and practice." } };

export default function ArticlesPage() {
  const publishedArticles = articles.filter((article) => article.reviewStatus === "approved");
  const categories = Array.from(new Set(publishedArticles.map((article) => article.category)));
  return <><SiteHeader /><main><section className="articles-hero"><div className="container"><p className="eyebrow">Articles and learning guides</p><h1>Useful answers for the questions between lessons.</h1><p className="hero-lede">A small, carefully edited library for learners who want to understand a rule, choose a starting point, or practise with more intention.</p></div></section><section className="section"><div className="container article-library">{categories.map((category) => <section key={category} className="article-category"><div className="article-category-heading"><p className="eyebrow">{category}</p><h2>{category === "Tajweed Basics" ? "Start with the larger picture" : category === "Tajweed Rules" ? "Make rule names useful" : category === "Learning Tips" ? "Build a steady practice" : "Read with more awareness"}</h2></div><div className="article-grid">{publishedArticles.filter((article) => article.category === category).map((article) => <a className="article-card" href={`/articles/${article.slug}`} key={article.slug}><span className="badge">{article.readingTime}</span><h3>{article.title}</h3><p className="muted">{article.description}</p><span className="text-link">Read the guide <ArrowRight size={14} /></span></a>)}</div></section>)}</div></section></main><Footer /></>;
}
